// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT

declare const Clipboard$1: any;
declare const React$1: typeof import('react');
declare const ReactNative$1: typeof import('react-native');
export declare const Assets: any;
export declare const Clyde: any;
export declare const Commands: any;
export declare const Constants: any;
export declare const Dispatcher: any;
export declare const Flux: any;
export declare const Gestures: any;
export declare const MarkdownParser: any;
export declare const Moment: any;
export declare const REST: any;
export declare const Radius: any;
export declare const Reanimated: any;
export declare const SVG: any;
export declare const Screens: any;
export declare const Util: any;
export declare const i18n: any;

export { Clipboard$1 as Clipboard, React$1 as React, ReactNative$1 as ReactNative };

export {};
