// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT

export type { DesignModule } from '../_internal';
import { ComponentType, ReactNode } from 'react';
import {
	ImageStyle,
	StyleProp,
	TextInputProps as RNTextInputProps,
	TextStyle,
	ViewProps,
	ViewStyle,
} from 'react-native';
export declare const BackdropFilters: any;
export declare const Discord: DesignModule;
export declare const FlashList: any;
export declare const Forms: any;
export declare const HelpMessage: any;
export declare const Media: any;
export declare const Portal: any;
export declare const SafeArea: any;
export {};
