// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT

import type { PredicateResult } from '../utils';
declare const CACHE_KEY: unique symbol;
declare const _default: {
	byProps: typeof byProps;
	byDisplayName: typeof byDisplayName;
	byPrototypes: typeof byPrototypes;
	byName: typeof byName;
	byStore: typeof byStore;
	byFilePath: typeof byFilePath;
};
/**
 * @description Builds a filter matching a module whose `displayName` equals the given name.
 * @param name The `displayName` the module must have.
 * @returns A {@link MetroFilter} matching the module with that `displayName`.
 */
export declare function byDisplayName(name: string): MetroFilter;
/**
 * @description Builds a filter matching a module whose tracked file path equals the given path.
 * @param path The file path the module must have been imported from.
 * @returns A {@link MetroFilter} matching the module loaded from that file path.
 */
export declare function byFilePath(path: string[]): MetroFilter;
/**
 * @description Builds a filter matching a module whose `name` equals the given name.
 * @param name The `name` the module must have.
 * @returns A {@link MetroFilter} matching the module with that `name`.
 */
export declare function byName(name: string): MetroFilter;
/**
 * @description Builds a filter matching a module that exposes all of the given property names.
 * @param props The property names the module must expose.
 * @returns A {@link MetroFilter} matching modules that expose every given property.
 */
export declare function byProps(...props: string[]): MetroFilter;
/**
 * @description Builds a filter matching a module whose prototype exposes all of the given method names.
 * @param prototypes The prototype method names the module's prototype must expose.
 * @returns A {@link MetroFilter} matching modules whose prototype exposes every given method.
 */
export declare function byPrototypes(...prototypes: string[]): MetroFilter;
/**
 * @description Builds a filter matching a flux store by name, appending `Store` when `short` is set.
 * @param name The store name to match against.
 * @param short Whether to append `Store` to `name` before matching.
 * @returns A {@link MetroFilter} matching the flux store with that name.
 */
export declare function byStore(name: string, short?: boolean): MetroFilter;
/** A module predicate, carrying its cache key and a `raw` flag, produced by every `by*` helper. */
export type MetroFilter = ((mdl: any, id: number | string) => PredicateResult) & {
	[CACHE_KEY]?: string;
	isRaw?: boolean;
};
export { _default as default };
