// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT

import {
	ImageStyle,
	StyleProp,
	TextInputProps as RNTextInputProps,
	TextStyle,
	ViewProps,
	ViewStyle,
} from 'react-native';
import { ComponentType, ReactNode } from 'react';

import type { AnyProps, Fn, PredicateResult } from '../utils';
/** @internal */
declare const CACHE_KEY: unique symbol;
export declare const off: typeof removeListener;
export declare const on: typeof addListener;
/**
 * @description Registers a listener invoked with every module as it is required.
 * @param listener Callback receiving the module exports and its id.
 * @returns A function that removes the listener.
 */
export declare function addListener(listener: (mdl: any, id: string) => void): () => boolean;
/**
 * @description Runs several filters in a single registry pass, returning one result per item.
 * @param items The filters to resolve, each with its own per-item options.
 * @returns An array of matches positionally aligned with `items`.
 */
export declare function bulk(...items: MetroBulkItem[]): any[];
/**
 * @description Core synchronous module search. Tries the per-key cache fast-path first, then falls
 * back to scanning the registry, degrading gracefully if the supplied filter throws.
 * @param filter The filter to match modules against.
 * @param options Search options controlling interop, caching, esModule unwrapping, and `all`.
 * @returns The first matching module, an array of matches when `all` is set, or `null`.
 */
export declare function find(filter: MetroFilter, options?: MetroSearchOptions): any;
/**
 * @description Finds a module by a segment of its file path.
 * @template U The union of requested path segments.
 * @template T The argument tuple, optionally ending in search options or a bulk marker.
 * @param args The file path segment(s) to search for, optionally followed by options.
 * @returns The matched module.
 */
export declare function findByFilePath<
	U extends string,
	T extends U[] | MetroStringFindWithOptions<U> | MetroBulkFind<U>,
>(...args: T): AnyProps;
/**
 * @description Finds a module by the name of its default export.
 * @template U The union of requested names.
 * @template T The argument tuple, optionally ending in search options or a bulk marker.
 * @param args The name(s) to search for, optionally followed by options.
 * @returns The matched function (or matches, for a bulk/`all` search).
 */
export declare function findByName<
	U extends string,
	T extends U[] | MetroStringFindWithOptions<U> | MetroBulkFind<U>,
>(...args: T): MetroFunctionSignatureOrArray<T, U>;
/**
 * @description Finds a module exposing all of the given property names.
 * @template U The union of requested property names.
 * @template T The argument tuple, optionally ending in search options or a bulk marker.
 * @param args The property names to search for, optionally followed by options.
 * @returns The matched module (or matches, for a bulk/`all` search).
 */
export declare function findByProps<
	U extends string,
	T extends U[] | MetroStringFindWithOptions<U> | MetroBulkFind<U>,
>(...args: T): MetroPropertyRecordOrArray<T, U> & {};
/**
 * @description Finds a module whose prototype exposes all of the given method names.
 * @template U The union of requested prototype method names.
 * @template T The argument tuple, optionally ending in search options or a bulk marker.
 * @param args The prototype method names to search for, optionally followed by options.
 * @returns The matched module.
 */
export declare function findByPrototypes<
	U extends string,
	T extends U[] | MetroStringFindWithOptions<U> | MetroBulkFind<U>,
>(...args: T): AnyProps;
/**
 * @description Resolves a module matching `filter`, waiting for it to load if it is not yet present.
 * @param filter The filter to match against.
 * @param options Search options, excluding `lazy` and `all`, plus an optional `signal` to abort the wait.
 * @returns The matched module, or a promise that resolves once a matching module is required, or
 * `undefined` if the supplied signal aborts first.
 */
export declare function findLazy(filter: MetroFilter, options?: MetroLazySearchOptions): any;
/**
 * @description Finds a flux store by name.
 * @template U The union of requested store names.
 * @template T The argument tuple, optionally ending in store search options.
 * @param args The store name(s) to search for, optionally followed by options (`short` defaults to `true`).
 * @returns The matched store.
 */
export declare function findStore<
	U extends string,
	T extends U[] | MetroStringFindWithOptions<U, MetroStoreOptions>,
>(...args: T): AnyProps;
/**
 * @description Forces a module to initialise via metro's `__r`, blacklisting it if it throws.
 * @param id The id of the module to initialise.
 * @returns `true` if the module is initialised, `false` if it was blacklisted.
 */
export declare function initializeModule(id: number): boolean;
/**
 * @description Removes a previously registered module listener.
 * @param listener The listener to remove.
 */
export declare function removeListener(listener: (mdl: any, id: string) => void): void;

/** A single entry in a {@link bulk} search: a filter plus its per-item options. */
export interface MetroBulkItem extends Omit<MetroSearchOptions, 'initial' | 'cache'> {
	filter: MetroFilter;
}
/** Search options for {@link findLazy}, adding a `signal` that abandons the wait when aborted. */
export interface MetroLazySearchOptions extends Omit<MetroSearchOptions, 'lazy' | 'all'> {
	signal?: AbortSignal;
}
/** Search options for {@link findStore}, adding the `short` name-matching toggle. */
export interface MetroStoreOptions extends MetroSearchOptions {
	short?: boolean;
}

/** Widens a single result to an array when the search was made with `all: true`. */
export type MetroAllValues<T extends Record<PropertyKey, any>, U extends unknown> = T extends {
	all: true;
}
	? U[]
	: U;
/** Tuple of param bags followed by a `{ bulk: true }` marker, describing a bulk find. */
export type MetroBulkFind<T extends string> = [
	...AnyProps<MetroParamsBag<T>>[],
	AnyProps<MetroBulkMarker>,
];
/** The marker object distinguishing a bulk find from a single one. */
export type MetroBulkMarker = {
	bulk: true;
};
/** Result shape of a bulk by-name search, one function per requested item. */
export type MetroBulkModuleByName<T extends any[]> = {
	[K in keyof T]: T[K] extends {
		interop: false;
	}
		? {
				default: Fn;
			}
		: Fn;
};
/** Result shape of a bulk by-property search, one record per requested item. */
export type MetroBulkModuleByProperty<T extends any[]> = {
	[K in keyof T]: AnyProps<MetroParamsRecord<T[K]['params']>>;
};
/** A module predicate, carrying its cache key and a `raw` flag, produced by every `by*` helper. */
export type MetroFilter = ((mdl: any, id: number | string) => PredicateResult) & {
	[CACHE_KEY]?: string;
	isRaw?: boolean;
};
/** Dispatches to the bulk or single by-name result shape based on the argument tuple. */
export type MetroFunctionSignatureOrArray<T extends any[], U extends string> =
	T extends MetroBulkFind<U> ? MetroBulkModuleByName<T> : MetroSingleModuleByName<T>;
/** Options that control internal search behaviour shared across every `findBy*` helper. */
export type MetroInternalOptions = {
	bulk?: boolean;
	lazy?: boolean;
};
/** Convenience alias for a by-property result derived from a union of prop names. */
export type MetroModule<TProps extends string> = MetroPropertyRecordOrArray<TProps[], TProps>;
/** A bag carrying a `params` array of prop names. */
export type MetroParamsBag<T extends string> = {
	params: T[];
};
/** A record keyed by the prop names listed in a single bulk item's `params`. */
export type MetroParamsRecord<Params extends PropertyKey[]> = {
	[P in Params[number]]: any;
};
/** Dispatches to the bulk or single by-property result shape based on the argument tuple. */
export type MetroPropertyRecordOrArray<T extends any[], U extends string> =
	T extends MetroBulkFind<U> ? MetroBulkModuleByProperty<T> : MetroSingleModuleByProperty<T>;
/** A record keyed by the non-options entries of a find argument tuple. */
export type MetroPropsRecord<T extends any[]> = {
	[k in Exclude<T[number], Record<PropertyKey, any>>]: any;
};
/** Public options accepted by {@link find} and the `findBy*` family. */
export type MetroSearchOptions = {
	esModules?: boolean;
	interop?: boolean;
	initial?: any[];
	cache?: boolean;
	lazy?: boolean;
	raw?: boolean;
	all?: boolean;
	initialize?: boolean;
};
/** Result shape of a by-name search: the matched function (or its default export). */
export type MetroSingleModuleByName<T extends any[]> = T extends [
	...any,
	infer O extends MetroSearchOptions,
]
	? MetroAllValues<
			O,
			O extends {
				interop: false;
			}
				? {
						default: Fn;
					}
				: Fn
		>
	: Fn;
/** Result shape of a by-property search: a record keyed by the requested props. */
export type MetroSingleModuleByProperty<T extends any[]> = T extends [
	...any,
	infer O extends MetroSearchOptions,
]
	? MetroAllValues<O, AnyProps<MetroPropsRecord<T>>>
	: AnyProps<MetroPropsRecord<T>>;
/** Tuple of search terms followed by a trailing options object. */
export type MetroStringFindWithOptions<T extends string, Options = MetroSearchOptions> = [
	...T[],
	Options,
];
export * as components from './components';
export * as filters from './filters';
export * as common from './common';
export * as stores from './stores';
export * as api from './api';
