import { join, dirname, resolve, relative, sep } from 'node:path';
import { readFileSync } from 'node:fs';
import Logger from '@unbound-app/logger';

import { config } from '../../sdk.config.ts';

export const logger = Logger.create('SDK');

export const ROOT = join(__dirname, '..', '..', '..', '..');
export const CLIENT = join(ROOT, 'packages', 'client');
export const API_SRC = resolveOutDir(ROOT, config.outDir);
export const SDK_TSCONFIG = join(CLIENT, 'tsconfig.sdk.json');
export const BARREL = resolve(ROOT, config.barrelPath);

/** The `~/` path alias maps to the client package's `src/` directory. */
export const ALIAS_ROOT = join(CLIENT, 'src');

export const BANNER = '// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT';

export const INLINED_LIBRARIES = config.inlinedLibraries;

/** The `@unbound-app/types` index; its bundle feeds the `_internal` hoist file and the globals. */
export const TYPES_INDEX = join(ROOT, 'packages', 'types', 'index.d.ts');

/** The `@unbound-app/types/utils` typings; its bundle is the public `utils` hoist file. */
export const UTILS_INDEX = join(ROOT, 'packages', 'types', 'typings', 'utils.ts');

/** The generated home for the public utility types (`Fn`, `Widen`, …), imported relative to modules. */
export const UTILS_OUT = join(API_SRC, 'utils.d.ts');

/** The generated home for the non-public shared `@unbound-app/types` surface; also feeds `global.d.ts`. */
export const INTERNAL_OUT = join(API_SRC, '_internal.d.ts');

export type ModuleEntry = {
	name: string;
	source: string;
	out: string;
	/** Top-level capability modules type `window.unbound.*`; nested subpaths live inside their parent. */
	topLevel: boolean;
};

/**
 * @description Computes the relative module specifier from a file at `fromOut` to a hoist file at
 * `toOut`, so nested modules (`metro/index.d.ts`) reach up to a top-level hoist file.
 * @param fromOut The absolute output path of the importing file.
 * @param toOut The absolute output path of the hoist file being imported.
 * @returns The POSIX-style relative module specifier, without extension.
 */
export function relativeSpecifier(fromOut: string, toOut: string): string {
	const rel = relative(dirname(fromOut), toOut)
		.replace(/\.d\.ts$/, '')
		.split('\\')
		.join('/');

	return rel.startsWith('.') ? rel : `./${rel}`;
}

/**
 * @description Resolves the configured output directory and guards the generator's destructive
 * clean step: the resolved path must sit strictly inside the repository, so a misconfigured
 * `outDir` can never point `rmSync` at the repo root or anything outside it.
 * @param root The absolute repository root.
 * @param outDir The configured output directory, relative to the repository root.
 * @returns The validated absolute output directory.
 */
export function resolveOutDir(root: string, outDir: string): string {
	const resolved = resolve(root, outDir);

	if (resolved === root || !resolved.startsWith(root + sep)) {
		throw new Error(
			`config.outDir must resolve to a directory inside the repository, got '${resolved}'.`,
		);
	}

	return resolved;
}

/**
 * @description Reads and parses a JSON object file, naming the file in the error so a malformed
 * or non-object manifest is attributable at a glance.
 * @param path The absolute path of the JSON file to read.
 * @returns The parsed object.
 */
export function readJson(path: string): Record<string, any> {
	let parsed: unknown;

	try {
		parsed = JSON.parse(readFileSync(path, 'utf8'));
	} catch (error: any) {
		throw new Error(`Failed to parse JSON from '${path}': ${error.message}`);
	}

	if (parsed === null || typeof parsed !== 'object') {
		throw new Error(`Expected a JSON object in '${path}'.`);
	}

	return parsed as Record<string, any>;
}
