import { join, dirname, resolve, relative } from 'node:path';
import { createRequire } from 'node:module';
import Logger from '@unbound-app/logger';

import { config } from '../../sdk.config.ts';

export const logger = Logger.create('SDK');

export const ROOT = join(__dirname, '..', '..', '..', '..');
export const CLIENT = join(ROOT, 'packages', 'client');
export const API_SRC = resolve(ROOT, config.outDir);
export const SDK_TSCONFIG = join(CLIENT, 'tsconfig.sdk.json');
export const BARREL = resolve(ROOT, config.barrelPath);

/** The `~/` path alias maps to the client package's `src/` directory. */
export const ALIAS_ROOT = join(CLIENT, 'src');

export const BANNER = '// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT';

export const INLINED_LIBRARIES = config.inlinedLibraries;

/** The `@unbound-app/types` index; its bundle is the `utilities` hoist file that also feeds the globals. */
export const TYPES_INDEX = join(ROOT, 'packages', 'types', 'index.d.ts');

/** The generated home for the shared `@unbound-app/types` types; also the source for `global.d.ts`. */
export const UTILITIES_OUT = join(API_SRC, 'utilities.d.ts');

/** Resolves a bare module specifier from the client package, where the inlined libraries are installed. */
export const clientRequire = createRequire(join(CLIENT, 'package.json'));

export type ModuleEntry = {
	name: string;
	source: string;
	out: string;
	/** Top-level capability modules type `window.unbound.*`; nested subpaths live inside their parent. */
	topLevel: boolean;
};

/**
 * @description Computes the relative module specifier from a file at `fromOut` to a hoist file at
 * `toOut`, so nested modules (`metro/index.d.ts`) reach up to a top-level hoist file.
 * @param fromOut The absolute output path of the importing file.
 * @param toOut The absolute output path of the hoist file being imported.
 * @returns The POSIX-style relative module specifier, without extension.
 */
export function relativeSpecifier(fromOut: string, toOut: string): string {
	const rel = relative(dirname(fromOut), toOut)
		.replace(/\.d\.ts$/, '')
		.split('\\')
		.join('/');

	return rel.startsWith('.') ? rel : `./${rel}`;
}
