import { generateDtsBundle, type EntryPointConfig } from 'dts-bundle-generator';
import { writeFileSync, readFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import { Project, Node, SyntaxKind } from 'ts-morph';
import { join, dirname, resolve, relative } from 'node:path';
import { execSync } from 'node:child_process';
import { createHash } from 'node:crypto';

import Logger from '../packages/logger/src/index.ts';
import { config } from '../packages/api/sdk.config.ts';

const logger = Logger.create('SDK');

const ROOT = join(__dirname, '..');
const CLIENT = join(ROOT, 'packages', 'client');
const API_SRC = resolve(ROOT, config.outDir);
const SDK_TSCONFIG = join(CLIENT, 'tsconfig.sdk.json');
const BARREL = resolve(ROOT, config.barrelPath);

/** The `~/` path alias maps to the client package's `src/` directory. */
const ALIAS_ROOT = join(CLIENT, 'src');

const BANNER = '// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT';

const INLINED_LIBRARIES = config.inlinedLibraries;

type ModuleEntry = {
	name: string;
	source: string;
	out: string;
	/** Top-level capability modules type `window.unbound.*`; nested subpaths live inside their parent. */
	topLevel: boolean;
};

/**
 * @description Resolves a module specifier from a barrel to its source `.ts` file. Handles the `~/`
 * alias (mapped to the client `src/`) and relative specifiers, returning either the flat `<path>.ts`
 * or the folder barrel `<path>/index.ts`, whichever exists.
 * @param specifier The raw module specifier (`~/api/metro`, `./filters`, …).
 * @param fromDir The directory of the barrel the specifier was written in, for relative resolution.
 * @returns The absolute source path, or `undefined` if neither a flat file nor a folder barrel exists.
 */
function resolveSource(specifier: string, fromDir: string): string | undefined {
	const base = specifier.startsWith('~/')
		? join(ALIAS_ROOT, specifier.slice(2))
		: resolve(fromDir, specifier);

	if (existsSync(`${base}.ts`)) return `${base}.ts`;
	if (existsSync(join(base, 'index.ts'))) return join(base, 'index.ts');

	return void 0;
}

/**
 * @description Reads a barrel's `export * as <name> from '<specifier>'` re-exports, skipping any tagged
 * `@internal`. This is the single source of truth for the public module surface - the managers line
 * uses `export { … }` (not `export * as`) and is excluded automatically.
 * @param barrel The absolute path to the barrel file to parse.
 * @returns The namespace name and resolved source for each surviving re-export.
 */
function readNamespaceExports(barrel: string): { name: string; source: string }[] {
	const project = new Project({ useInMemoryFileSystem: true });
	const sourceFile = project.createSourceFile('barrel.ts', readFileSync(barrel, 'utf8'));
	const fromDir = dirname(barrel);

	const namespaces: { name: string; source: string }[] = [];

	for (const declaration of sourceFile.getExportDeclarations()) {
		const alias = declaration.getNamespaceExport();
		if (!alias) continue;
		if (isInternal(declaration)) continue;

		const name = alias.getName();
		if (!name) continue;

		const specifier = declaration.getModuleSpecifierValue();
		if (!specifier) continue;

		const source = resolveSource(specifier, fromDir);
		if (!source) continue;

		namespaces.push({ name, source });
	}

	return namespaces;
}

/**
 * @description Builds the ordered entry list by parsing the api barrel and recursing into folder
 * modules for their nested `export * as` sub-namespaces (e.g. `metro/filters`). A module is a folder
 * when its source resolves to an `index.ts`; each nested namespace becomes a `<parent>/<child>`
 * subpath entry. Auto-derived subpaths in `config.excludeSubpaths` are skipped; `config.additionalSubpaths`
 * are appended.
 * @returns The entry descriptors (root first) sorted so the output is deterministic across runs.
 */
function buildEntries(): ModuleEntry[] {
	const entries: ModuleEntry[] = [];

	const outFor = (name: string) => join(API_SRC, ...name.split('/')) + '.d.ts';

	function walk(barrel: string, prefix: string, topLevel: boolean) {
		for (const { name, source } of readNamespaceExports(barrel)) {
			const subpath = prefix ? `${prefix}/${name}` : name;
			if (config.excludeSubpaths.includes(subpath)) continue;

			const isFolder = source.endsWith('index.ts');
			const out = isFolder
				? join(API_SRC, ...subpath.split('/'), 'index.d.ts')
				: outFor(subpath);

			entries.push({ name: subpath, source, out, topLevel });

			if (isFolder) walk(source, subpath, false);
		}
	}

	walk(BARREL, '', true);

	for (const extra of config.additionalSubpaths) {
		const source = resolve(dirname(BARREL), extra.source);
		if (config.excludeSubpaths.includes(extra.name)) continue;

		entries.push({ name: extra.name, source, out: outFor(extra.name), topLevel: false });
	}

	const root: ModuleEntry = {
		name: '.',
		source: BARREL,
		out: join(API_SRC, 'index.d.ts'),
		topLevel: false,
	};

	entries.sort((a, b) => a.name.localeCompare(b.name));

	return [root, ...entries.filter((entry) => entry.name !== '.')];
}

/**
 * @description Runs `dts-bundle-generator` over a single source file, inlining the workspace
 * libraries and leaving react/react-native external.
 * @param source The absolute path to the entry's source file.
 * @param inlineDeclareGlobals Whether to inline `declare global` blocks (only the globals bundle needs them).
 * @returns The flattened `.d.ts` bundle as a string.
 */
function bundle(source: string, inlineDeclareGlobals: boolean = false): string {
	const entry: EntryPointConfig = {
		filePath: source,
		libraries: { inlinedLibraries: INLINED_LIBRARIES },
		output: { noBanner: true, inlineDeclareGlobals, sortNodes: true },
	};

	const [result] = generateDtsBundle([entry], { preferredConfigPath: SDK_TSCONFIG });

	return result;
}

/**
 * @description Tests whether a JSDocable node carries an `@internal` tag in its leading documentation.
 * @param node The node to inspect.
 * @returns `true` when the node is tagged `@internal`.
 */
function isInternal(node: Node): boolean {
	if (!Node.isJSDocable(node)) return false;

	return node
		.getJsDocs()
		.some((doc) => doc.getTags().some((tag) => tag.getTagName() === 'internal'));
}

/**
 * @description Recursively removes `@internal`-tagged declarations from a statement container,
 * descending into `declare global`/module bodies and pruning `@internal` interface members. An
 * `@internal` declaration is retained when a surviving (non-`@internal`) statement in the same
 * container still references its name - a public type may keep a bare backing declaration structurally
 * alive (e.g. `MetroFilter` referencing the internal `[CACHE_KEY]` symbol), and removing it would
 * leave a dangling reference. Keeping such a declaration is not a leak: it wears no `export` modifier.
 * @param container A source file or module body exposing `getStatements`.
 * @param internalNames Collects the names of removed top-level declarations so namespace re-export
 * lists referencing them can be pruned afterwards.
 * @param retainedInternalNames Collects the names of `@internal` declarations that were kept as
 * ambient backing declarations. They are retained for structural type resolution only, never to be
 * re-exported, so namespace re-export lists referencing them must still be pruned.
 */
function stripInternal(
	container: Node,
	internalNames: Set<string>,
	retainedInternalNames: Set<string>,
) {
	if (!Node.isStatemented(container)) return;

	const candidates = new Map<Node, string[]>();
	const survivors: Node[] = [];

	for (const statement of container.getStatements()) {
		if (isInternal(statement)) {
			candidates.set(statement, declaredNames(statement));
			continue;
		}

		survivors.push(statement);

		if (Node.isModuleDeclaration(statement)) {
			const body = statement.getBody();
			if (body) stripInternal(body, internalNames, retainedInternalNames);
		}

		if (Node.isInterfaceDeclaration(statement)) {
			for (const member of statement.getMembers()) {
				if (isInternal(member)) member.remove();
			}
		}
	}

	const referenced = collectReferencedNames(survivors);

	for (const [statement, names] of candidates) {
		if (names.some((name) => referenced.has(name))) {
			// A retained backing declaration must not be part of the module's public surface: drop its
			// `export` so it stays an ambient `declare`, matching how the same symbol appears in the
			// bundles that never re-export it (e.g. `metro/filters.d.ts`, root `index.d.ts`).
			if (Node.isModifierable(statement)) statement.toggleModifier('export', false);

			for (const name of names) retainedInternalNames.add(name);

			continue;
		}

		for (const name of names) internalNames.add(name);

		statement.remove();
	}
}

/**
 * @description Collects every top-level declaration name that the given statements reference. Uses
 * the same reference classification as the root tree-shaker: aliased/import specifier names and a
 * declaration's own name node don't count, but a computed `[X]` property name is a real reference.
 * @param statements The surviving statements to scan for references.
 * @returns The set of referenced identifier texts.
 */
function collectReferencedNames(statements: Node[]): Set<string> {
	const referenced = new Set<string>();

	for (const statement of statements) {
		for (const reference of statement.getDescendantsOfKind(SyntaxKind.Identifier)) {
			if (!isReference(reference)) continue;

			referenced.add(reference.getText());
		}
	}

	return referenced;
}

/**
 * @description Reports whether an identifier is a genuine reference to a declaration rather than a
 * binding or specifier name. An aliased export specifier (`X as Y`) references only `X`; an import
 * specifier's names are re-bindings, not references; a declaration's own name node is not a
 * reference. A computed `[X]` property name stays a reference (handled by `isDeclarationName`).
 * @param reference The identifier to classify.
 */
function isReference(reference: Node): boolean {
	const parent = reference.getParent();

	if (Node.isExportSpecifier(parent)) {
		if (parent.getAliasNode() === reference) return false;
	} else if (Node.isImportSpecifier(parent)) {
		return false;
	} else if (isDeclarationName(reference)) {
		return false;
	}

	return true;
}

/**
 * @description Lists the binding names a top-level declaration introduces.
 * @param statement The declaration to inspect.
 * @returns The declared identifier names (empty for anonymous statements).
 */
function declaredNames(statement: Node): string[] {
	if (Node.isVariableStatement(statement)) {
		return statement.getDeclarations().map((declaration) => declaration.getName());
	}

	if (
		Node.isFunctionDeclaration(statement) ||
		Node.isClassDeclaration(statement) ||
		Node.isInterfaceDeclaration(statement) ||
		Node.isTypeAliasDeclaration(statement) ||
		Node.isEnumDeclaration(statement)
	) {
		const name = statement.getName();
		return name ? [name] : [];
	}

	return [];
}

/**
 * @description Removes named specifiers from `declare namespace X { export { ... } }` re-export lists
 * whose exported name matches an `@internal` binding stripped from that module's own bundle. The
 * root bundle re-exports each capability as a namespace, where the inlined member's `@internal`
 * JSDoc is lost, so the tag can no longer be honoured directly. A retained-internal symbol - kept as
 * an ambient backing declaration for structural type resolution (e.g. `CACHE_KEY` backing the public
 * `MetroFilter`) - is likewise pruned from the list: it survives the bundle to resolve a type, not to
 * be re-exported on the namespace.
 * @param sourceFile The parsed root bundle.
 * @param internalByModule A map of capability module name to the set of `@internal` member names
 * collected while stripping that module's own bundle.
 * @param retainedByModule A map of capability module name to the set of `@internal` member names that
 * were retained as backing declarations while stripping that module's own bundle.
 */
function pruneNamespaceMembers(
	sourceFile: Node,
	internalByModule: Map<string, Set<string>>,
	retainedByModule: Map<string, Set<string>>,
) {
	if (!Node.isStatemented(sourceFile)) return;

	const internalEverywhere = new Set<string>();
	for (const names of internalByModule.values()) {
		for (const name of names) internalEverywhere.add(name);
	}
	for (const names of retainedByModule.values()) {
		for (const name of names) internalEverywhere.add(name);
	}

	for (const statement of sourceFile.getStatements()) {
		if (!Node.isModuleDeclaration(statement)) continue;

		const name = statement.getName();
		const scoped = internalByModule.get(name);
		const retained = retainedByModule.get(name);

		const forbidden =
			scoped || retained
				? new Set([...(scoped ?? []), ...(retained ?? [])])
				: internalEverywhere;

		const body = statement.getBody();
		if (!body || !Node.isStatemented(body)) continue;

		for (const inner of body.getStatements()) {
			if (!Node.isExportDeclaration(inner)) continue;

			for (const specifier of inner.getNamedExports()) {
				const exported = specifier.getAliasNode()?.getText() ?? specifier.getName();
				if (forbidden.has(exported)) specifier.remove();
			}
		}
	}
}

/**
 * @description Reports whether an identifier is the declared name of its parent (a parameter,
 * a property/method signature, a property/variable name, ...) rather than a reference to a
 * declaration. ts-morph exposes the declared name via `getNameNode`, so an identifier that is
 * exactly its parent's name node is a declaration name. A computed `[X]` property name is a real
 * reference to `X`, so it is excluded.
 * @param reference The identifier to classify.
 */
function isDeclarationName(reference: Node): boolean {
	const parent = reference.getParent() as { getNameNode?: () => Node | undefined };
	if (typeof parent.getNameNode !== 'function') return false;
	if (parent.getNameNode() !== reference) return false;

	return !Node.isComputedPropertyName(reference.getParent());
}

/**
 * @description Tree-shakes the root bundle against its real public surface. The api barrel exports
 * only its capability namespaces, so the true roots are the final `export { ... }` block and the
 * `declare namespace` re-exports. Every top-level declaration dts-bundle-generator hoisted (whether
 * or not it wears an `export` modifier) is kept only when reachable from those roots; the rest -
 * notably the manager types orphaned once the `@internal` manager consts are stripped - are removed.
 * @param sourceFile The parsed root bundle to tree-shake.
 */
function pruneUnreferenced(sourceFile: Node) {
	if (!Node.isStatemented(sourceFile)) return;

	const byName = new Map<string, Node[]>();

	for (const statement of sourceFile.getStatements()) {
		for (const name of declaredNames(statement)) {
			const bucket = byName.get(name) ?? [];
			bucket.push(statement);
			byName.set(name, bucket);
		}
	}

	const roots: Node[] = [];
	for (const statement of sourceFile.getStatements()) {
		if (Node.isExportDeclaration(statement) || Node.isModuleDeclaration(statement)) {
			roots.push(statement);
		}
	}

	const reachable = new Set<Node>();
	const queue = [...roots];

	while (queue.length) {
		const statement = queue.pop()!;
		if (reachable.has(statement)) continue;
		reachable.add(statement);

		const isRoot = roots.includes(statement);

		for (const reference of statement.getDescendantsOfKind(SyntaxKind.Identifier)) {
			const parent = reference.getParent();

			// A namespace/export re-export lists its members by their local name; those specifier
			// identifiers are real references. But an aliased specifier (`X as Y`) references only
			// `X`, never `Y` - skip the alias so an aliased public name can't resurrect an internal
			// declaration that merely shares it.
			if (Node.isExportSpecifier(parent)) {
				if (parent.getAliasNode() === reference) continue;
			} else if (Node.isImportSpecifier(parent)) {
				continue;
			} else if (isRoot && Node.isModuleDeclaration(statement)) {
				// The namespace's own name and its `declare namespace` keyword aren't references.
				if (parent === statement) continue;
			} else if (isDeclarationName(reference)) {
				// The identifier that names a declaration (a parameter, a property/method signature, or a
				// property/variable name) is the declared name, not a reference to one, so it must not mark
				// a same-named top-level declaration reachable. Computed `[X]` names stay references.
				continue;
			}

			const targets = byName.get(reference.getText());
			if (!targets) continue;

			for (const target of targets) {
				if (target === statement) continue;
				if (!reachable.has(target)) queue.push(target);
			}
		}
	}

	for (const statement of sourceFile.getStatements()) {
		if (declaredNames(statement).length === 0) continue;
		if (reachable.has(statement)) continue;

		statement.remove();
	}
}

type StripResult = {
	text: string;
	internalNames: Set<string>;
	retainedInternalNames: Set<string>;
};

/**
 * @description Parses a bundle, strips its `@internal` declarations, and returns the cleaned text
 * alongside the set of `@internal` names removed.
 * @param text The raw bundle text.
 * @returns The stripped text, the collected internal names, and the retained-internal names.
 */
function strip(text: string): StripResult {
	const project = new Project({ useInMemoryFileSystem: true });
	const sourceFile = project.createSourceFile('bundle.d.ts', text);

	const internalNames = new Set<string>();
	const retainedInternalNames = new Set<string>();
	stripInternal(sourceFile, internalNames, retainedInternalNames);

	return { text: sourceFile.getFullText(), internalNames, retainedInternalNames };
}

/**
 * @description Strips the root bundle: removes `@internal` top-level declarations, prunes the
 * matching members from its capability namespaces, then tree-shakes the now-dead declarations.
 * @param text The raw root bundle text.
 * @param internalByModule Internal member names collected per capability module.
 * @param retainedByModule Retained-internal member names collected per capability module.
 * @returns The cleaned root bundle text.
 */
function stripRoot(
	text: string,
	internalByModule: Map<string, Set<string>>,
	retainedByModule: Map<string, Set<string>>,
): string {
	const project = new Project({ useInMemoryFileSystem: true });
	const sourceFile = project.createSourceFile('index.d.ts', text);

	stripInternal(sourceFile, new Set<string>(), new Set<string>());
	pruneNamespaceMembers(sourceFile, internalByModule, retainedByModule);
	pruneUnreferenced(sourceFile);

	return sourceFile.getFullText();
}

/**
 * @description Normalises a `.d.ts` file down to its structural surface: `@internal` already
 * stripped, all comments/JSDoc removed, whitespace collapsed. Used only for hashing so JSDoc and
 * formatting edits never flip the version hash.
 * @param text The formatted file text.
 * @returns The comment-free, whitespace-collapsed declaration text.
 */
function normalizeForHash(text: string): string {
	const withoutComments = text.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '');

	return withoutComments.replace(/\s+/g, ' ').trim();
}

/**
 * @description Emits the SDK's `global.d.ts`: the addon-facing globals and Discord/util types bundled
 * from `@unbound-app/types` (with `@internal` stripped), followed by the `UnboundGlobal` interface
 * that types `window.unbound` and the ambient `unbound` const from the per-module declarations.
 * @param entries The emitted module entries; only top-level capability modules appear on `unbound.*`.
 * @returns The `global.d.ts` file text (unformatted, no banner).
 */
function buildGlobal(entries: ModuleEntry[]): string {
	const typesBundle = bundle(join(ROOT, 'packages', 'types', 'index.d.ts'), true);
	const { text: strippedTypes } = strip(typesBundle);

	const members = entries
		.filter((entry) => entry.topLevel)
		.map((entry) => {
			const path = './' + relative(API_SRC, entry.out).split('\\').join('/');
			return `\t${entry.name}: typeof import('${path}');`;
		})
		.join('\n');

	const registry = [
		'export interface UnboundGlobal {',
		members,
		'}',
		'',
		'declare global {',
		'\tinterface Window {',
		'\t\tunbound: UnboundGlobal;',
		'\t}',
		'',
		"\tconst unbound: Window['unbound'];",
		'}',
	].join('\n');

	return `${strippedTypes}\n${registry}\n`;
}

/**
 * @description Rewrites `packages/api/package.json` with the derived version and the regenerated
 * `exports` map, preserving every other field.
 * @param version The `<client version>-<hash>` string to write.
 * @param entries The emitted module entries used to build the `exports` map.
 */
function writeManifest(version: string, entries: ModuleEntry[]) {
	const manifestPath = join(ROOT, 'packages', 'api', 'package.json');
	const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));

	const exports: Record<string, string> = {
		'.': './src/index.d.ts',
		'./global': './src/global.d.ts',
	};

	for (const entry of entries) {
		if (entry.name === '.') continue;

		const target = './src/' + relative(API_SRC, entry.out).split('\\').join('/');
		exports[`./${entry.name}`] = target;
	}

	const ordered: Record<string, string> = {};
	for (const key of Object.keys(exports).sort()) ordered[key] = exports[key];

	manifest.version = version;
	manifest.exports = ordered;

	writeFileSync(manifestPath, JSON.stringify(manifest, null, '\t') + '\n');
}

async function generate() {
	const start = performance.now();

	logger.debug('Generating plugin SDK...');

	rmSync(API_SRC, { recursive: true, force: true });
	mkdirSync(API_SRC, { recursive: true });

	const entries = buildEntries();

	const internalByModule = new Map<string, Set<string>>();
	const retainedByModule = new Map<string, Set<string>>();
	const outputs = new Map<string, string>();

	for (const entry of entries) {
		if (entry.name === '.') continue;

		const { text, internalNames, retainedInternalNames } = strip(bundle(entry.source));

		internalByModule.set(entry.name, internalNames);
		retainedByModule.set(entry.name, retainedInternalNames);
		outputs.set(entry.out, text);
	}

	const root = entries.find((entry) => entry.name === '.')!;
	outputs.set(root.out, stripRoot(bundle(root.source), internalByModule, retainedByModule));

	outputs.set(join(API_SRC, 'global.d.ts'), buildGlobal(entries));

	for (const [path, text] of outputs) {
		mkdirSync(dirname(path), { recursive: true });
		writeFileSync(path, `${BANNER}\n\n${text.trimStart()}`);
	}

	execSync(
		`oxfmt --config .oxfmtrc.json ${[...outputs.keys()].map((path) => `"${path}"`).join(' ')}`,
		{
			cwd: ROOT,
			stdio: 'inherit',
		},
	);

	const hash = createHash('sha256');
	for (const path of [...outputs.keys()].sort()) {
		hash.update(normalizeForHash(readFileSync(path, 'utf8')));
	}

	const clientVersion = JSON.parse(readFileSync(join(CLIENT, 'package.json'), 'utf8')).version;
	const version = `${clientVersion}-${hash.digest('hex')}`;

	writeManifest(version, entries);

	execSync(`oxfmt --config .oxfmtrc.json "${join(ROOT, 'packages', 'api', 'package.json')}"`, {
		cwd: ROOT,
		stdio: 'inherit',
	});

	const duration = (performance.now() - start).toFixed(2);

	logger.success(`Generated plugin SDK v${version} in ${duration}ms`);
}

if (import.meta.main) {
	generate().catch((error) => {
		logger.error('Failed to generate plugin SDK:', error);
		process.exit(1);
	});
}
