import { generateDtsBundle, type EntryPointConfig } from 'dts-bundle-generator';
import { writeFileSync, readFileSync, mkdirSync, rmSync } from 'node:fs';
import { Project, Node, SyntaxKind } from 'ts-morph';
import { execSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { join } from 'node:path';

import Logger from '../packages/logger/src/index.ts';

const logger = Logger.create('SDK');

const ROOT = join(__dirname, '..');
const CLIENT = join(ROOT, 'packages', 'client');
const API_SRC = join(ROOT, 'packages', 'api', 'src');
const SDK_TSCONFIG = join(CLIENT, 'tsconfig.sdk.json');

const BANNER = '// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT';

const INLINED_LIBRARIES = [
	'@unbound-app/types',
	'@unbound-app/logger',
	'@unbound-app/utils',
	'tseep',
	'possess',
];

type ModuleEntry = {
	name: string;
	source: string;
	out: string;
};

/** The capability modules re-exported from the api barrel via `export * as <name>`, in barrel order. */
const CAPABILITY_MODULES = [
	'settings',
	'patcher',
	'storage',
	'assets',
	'native',
	'toasts',
	'metro',
	'i18n',
	'fs',
] as const;

/**
 * @description Builds the ordered entry list: the root api barrel, one entry per capability module,
 * and the extra `metro/filters` subpath. `metro` is a folder module (`metro/index.ts`); every other
 * capability is a flat file (`<name>.ts`).
 * @returns The entry descriptors sorted so the output is deterministic across runs.
 */
function buildEntries(): ModuleEntry[] {
	const apiDir = join(CLIENT, 'src', 'api');

	const modules: ModuleEntry[] = CAPABILITY_MODULES.map((name) => {
		const source =
			name === 'metro' ? join(apiDir, 'metro', 'index.ts') : join(apiDir, `${name}.ts`);
		const out =
			name === 'metro' ? join(API_SRC, 'metro', 'index.d.ts') : join(API_SRC, `${name}.d.ts`);

		return { name, source, out };
	});

	modules.push({
		name: 'metro/filters',
		source: join(apiDir, 'metro', 'filters.ts'),
		out: join(API_SRC, 'metro', 'filters.d.ts'),
	});

	const root: ModuleEntry = {
		name: '.',
		source: join(apiDir, 'index.ts'),
		out: join(API_SRC, 'index.d.ts'),
	};

	return [root, ...modules.sort((a, b) => a.name.localeCompare(b.name))];
}

/**
 * @description Runs `dts-bundle-generator` over a single source file, inlining the workspace
 * libraries and leaving react/react-native external.
 * @param source The absolute path to the entry's source file.
 * @param inlineDeclareGlobals Whether to inline `declare global` blocks (only the globals bundle needs them).
 * @returns The flattened `.d.ts` bundle as a string.
 */
function bundle(source: string, inlineDeclareGlobals: boolean = false): string {
	const entry: EntryPointConfig = {
		filePath: source,
		libraries: { inlinedLibraries: INLINED_LIBRARIES },
		output: { noBanner: true, inlineDeclareGlobals, sortNodes: true },
	};

	const [result] = generateDtsBundle([entry], { preferredConfigPath: SDK_TSCONFIG });

	return result;
}

/**
 * @description Tests whether a JSDocable node carries an `@internal` tag in its leading documentation.
 * @param node The node to inspect.
 * @returns `true` when the node is tagged `@internal`.
 */
function isInternal(node: Node): boolean {
	if (!Node.isJSDocable(node)) return false;

	return node
		.getJsDocs()
		.some((doc) => doc.getTags().some((tag) => tag.getTagName() === 'internal'));
}

/**
 * @description Recursively removes `@internal`-tagged declarations from a statement container,
 * descending into `declare global`/module bodies and pruning `@internal` interface members.
 * @param container A source file or module body exposing `getStatements`.
 * @param internalNames Collects the names of removed top-level declarations so namespace re-export
 * lists referencing them can be pruned afterwards.
 */
function stripInternal(container: Node, internalNames: Set<string>) {
	if (!Node.isStatemented(container)) return;

	for (const statement of container.getStatements()) {
		if (isInternal(statement)) {
			for (const name of declaredNames(statement)) internalNames.add(name);

			statement.remove();
			continue;
		}

		if (Node.isModuleDeclaration(statement)) {
			const body = statement.getBody();
			if (body) stripInternal(body, internalNames);
		}

		if (Node.isInterfaceDeclaration(statement)) {
			for (const member of statement.getMembers()) {
				if (isInternal(member)) member.remove();
			}
		}
	}
}

/**
 * @description Lists the binding names a top-level declaration introduces.
 * @param statement The declaration to inspect.
 * @returns The declared identifier names (empty for anonymous statements).
 */
function declaredNames(statement: Node): string[] {
	if (Node.isVariableStatement(statement)) {
		return statement.getDeclarations().map((declaration) => declaration.getName());
	}

	if (
		Node.isFunctionDeclaration(statement) ||
		Node.isClassDeclaration(statement) ||
		Node.isInterfaceDeclaration(statement) ||
		Node.isTypeAliasDeclaration(statement) ||
		Node.isEnumDeclaration(statement)
	) {
		const name = statement.getName();
		return name ? [name] : [];
	}

	return [];
}

/**
 * @description Removes named specifiers from `declare namespace X { export { ... } }` re-export lists
 * whose exported name matches an `@internal` binding stripped from that module's own bundle. The
 * root bundle re-exports each capability as a namespace, where the inlined member's `@internal`
 * JSDoc is lost, so the tag can no longer be honoured directly.
 * @param sourceFile The parsed root bundle.
 * @param internalByModule A map of capability module name to the set of `@internal` member names
 * collected while stripping that module's own bundle.
 */
function pruneNamespaceMembers(sourceFile: Node, internalByModule: Map<string, Set<string>>) {
	if (!Node.isStatemented(sourceFile)) return;

	const internalEverywhere = new Set<string>();
	for (const names of internalByModule.values()) {
		for (const name of names) internalEverywhere.add(name);
	}

	for (const statement of sourceFile.getStatements()) {
		if (!Node.isModuleDeclaration(statement)) continue;

		const scoped = internalByModule.get(statement.getName());
		const forbidden = scoped ?? internalEverywhere;

		const body = statement.getBody();
		if (!body || !Node.isStatemented(body)) continue;

		for (const inner of body.getStatements()) {
			if (!Node.isExportDeclaration(inner)) continue;

			for (const specifier of inner.getNamedExports()) {
				const exported = specifier.getAliasNode()?.getText() ?? specifier.getName();
				if (forbidden.has(exported)) specifier.remove();
			}
		}
	}
}

/**
 * @description Reports whether an identifier is the declared name of its parent (a parameter,
 * a property/method signature, a property/variable name, ...) rather than a reference to a
 * declaration. ts-morph exposes the declared name via `getNameNode`, so an identifier that is
 * exactly its parent's name node is a declaration name. A computed `[X]` property name is a real
 * reference to `X`, so it is excluded.
 * @param reference The identifier to classify.
 */
function isDeclarationName(reference: Node): boolean {
	const parent = reference.getParent() as { getNameNode?: () => Node | undefined };
	if (typeof parent.getNameNode !== 'function') return false;
	if (parent.getNameNode() !== reference) return false;

	return !Node.isComputedPropertyName(reference.getParent());
}

/**
 * @description Tree-shakes the root bundle against its real public surface. The api barrel exports
 * only its capability namespaces, so the true roots are the final `export { ... }` block and the
 * `declare namespace` re-exports. Every top-level declaration dts-bundle-generator hoisted (whether
 * or not it wears an `export` modifier) is kept only when reachable from those roots; the rest -
 * notably the manager types orphaned once the `@internal` manager consts are stripped - are removed.
 * @param sourceFile The parsed root bundle to tree-shake.
 */
function pruneUnreferenced(sourceFile: Node) {
	if (!Node.isStatemented(sourceFile)) return;

	const byName = new Map<string, Node[]>();

	for (const statement of sourceFile.getStatements()) {
		for (const name of declaredNames(statement)) {
			const bucket = byName.get(name) ?? [];
			bucket.push(statement);
			byName.set(name, bucket);
		}
	}

	const roots: Node[] = [];
	for (const statement of sourceFile.getStatements()) {
		if (Node.isExportDeclaration(statement) || Node.isModuleDeclaration(statement)) {
			roots.push(statement);
		}
	}

	const reachable = new Set<Node>();
	const queue = [...roots];

	while (queue.length) {
		const statement = queue.pop()!;
		if (reachable.has(statement)) continue;
		reachable.add(statement);

		const isRoot = roots.includes(statement);

		for (const reference of statement.getDescendantsOfKind(SyntaxKind.Identifier)) {
			const parent = reference.getParent();

			// A namespace/export re-export lists its members by their local name; those specifier
			// identifiers are real references. But an aliased specifier (`X as Y`) references only
			// `X`, never `Y` - skip the alias so an aliased public name can't resurrect an internal
			// declaration that merely shares it.
			if (Node.isExportSpecifier(parent)) {
				if (parent.getAliasNode() === reference) continue;
			} else if (Node.isImportSpecifier(parent)) {
				continue;
			} else if (isRoot && Node.isModuleDeclaration(statement)) {
				// The namespace's own name and its `declare namespace` keyword aren't references.
				if (parent === statement) continue;
			} else if (isDeclarationName(reference)) {
				// The identifier that names a declaration (a parameter, a property/method signature, or a
				// property/variable name) is the declared name, not a reference to one, so it must not mark
				// a same-named top-level declaration reachable. Computed `[X]` names stay references.
				continue;
			}

			const targets = byName.get(reference.getText());
			if (!targets) continue;

			for (const target of targets) {
				if (target === statement) continue;
				if (!reachable.has(target)) queue.push(target);
			}
		}
	}

	for (const statement of sourceFile.getStatements()) {
		if (declaredNames(statement).length === 0) continue;
		if (reachable.has(statement)) continue;

		statement.remove();
	}
}

/**
 * @description Parses a bundle, strips its `@internal` declarations, and returns the cleaned text
 * alongside the set of `@internal` names removed.
 * @param text The raw bundle text.
 * @returns The stripped text and the collected internal names.
 */
function strip(text: string): { text: string; internalNames: Set<string> } {
	const project = new Project({ useInMemoryFileSystem: true });
	const sourceFile = project.createSourceFile('bundle.d.ts', text);

	const internalNames = new Set<string>();
	stripInternal(sourceFile, internalNames);

	return { text: sourceFile.getFullText(), internalNames };
}

/**
 * @description Strips the root bundle: removes `@internal` top-level declarations, prunes the
 * matching members from its capability namespaces, then tree-shakes the now-dead declarations.
 * @param text The raw root bundle text.
 * @param internalByModule Internal member names collected per capability module.
 * @returns The cleaned root bundle text.
 */
function stripRoot(text: string, internalByModule: Map<string, Set<string>>): string {
	const project = new Project({ useInMemoryFileSystem: true });
	const sourceFile = project.createSourceFile('index.d.ts', text);

	stripInternal(sourceFile, new Set<string>());
	pruneNamespaceMembers(sourceFile, internalByModule);
	pruneUnreferenced(sourceFile);

	return sourceFile.getFullText();
}

/**
 * @description Normalises a `.d.ts` file down to its structural surface: `@internal` already
 * stripped, all comments/JSDoc removed, whitespace collapsed. Used only for hashing so JSDoc and
 * formatting edits never flip the version hash.
 * @param text The formatted file text.
 * @returns The comment-free, whitespace-collapsed declaration text.
 */
function normalizeForHash(text: string): string {
	const withoutComments = text.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '');

	return withoutComments.replace(/\s+/g, ' ').trim();
}

/**
 * @description Emits the SDK's `global.d.ts`: the addon-facing globals and Discord/util types bundled
 * from `@unbound-app/types` (with `@internal` stripped), followed by the `UnboundGlobal` interface
 * that types `window.unbound` and the ambient `unbound` const from the per-module declarations.
 * @returns The `global.d.ts` file text (unformatted, no banner).
 */
function buildGlobal(): string {
	const typesBundle = bundle(join(ROOT, 'packages', 'types', 'index.d.ts'), true);
	const { text: strippedTypes } = strip(typesBundle);

	const members = CAPABILITY_MODULES.map((name) => {
		const path = name === 'metro' ? './metro/index.d.ts' : `./${name}.d.ts`;
		return `\t${name}: typeof import('${path}');`;
	}).join('\n');

	const registry = [
		'export interface UnboundGlobal {',
		members,
		'}',
		'',
		'declare global {',
		'\tinterface Window {',
		'\t\tunbound: UnboundGlobal;',
		'\t}',
		'',
		"\tconst unbound: Window['unbound'];",
		'}',
	].join('\n');

	return `${strippedTypes}\n${registry}\n`;
}

/**
 * @description Rewrites `packages/api/package.json` with the derived version and the regenerated
 * `exports` map, preserving every other field.
 * @param version The `<client version>-<hash>` string to write.
 * @param entries The emitted module entries used to build the `exports` map.
 */
function writeManifest(version: string, entries: ModuleEntry[]) {
	const manifestPath = join(ROOT, 'packages', 'api', 'package.json');
	const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));

	const exports: Record<string, string> = {
		'.': './src/index.d.ts',
		'./global': './src/global.d.ts',
	};

	for (const entry of entries) {
		if (entry.name === '.') continue;

		const relative =
			'./src/' +
			entry.out
				.slice(API_SRC.length + 1)
				.split('\\')
				.join('/');
		exports[`./${entry.name}`] = relative;
	}

	const ordered: Record<string, string> = {};
	for (const key of Object.keys(exports).sort()) ordered[key] = exports[key];

	manifest.version = version;
	manifest.exports = ordered;

	writeFileSync(manifestPath, JSON.stringify(manifest, null, '\t') + '\n');
}

async function generate() {
	const start = performance.now();

	logger.debug('Generating plugin SDK...');

	rmSync(API_SRC, { recursive: true, force: true });
	mkdirSync(join(API_SRC, 'metro'), { recursive: true });

	const entries = buildEntries();

	const internalByModule = new Map<string, Set<string>>();
	const outputs = new Map<string, string>();

	for (const entry of entries) {
		if (entry.name === '.') continue;

		const { text, internalNames } = strip(bundle(entry.source));

		internalByModule.set(entry.name, internalNames);
		outputs.set(entry.out, text);
	}

	const root = entries.find((entry) => entry.name === '.')!;
	outputs.set(root.out, stripRoot(bundle(root.source), internalByModule));

	outputs.set(join(API_SRC, 'global.d.ts'), buildGlobal());

	for (const [path, text] of outputs) {
		writeFileSync(path, `${BANNER}\n\n${text.trimStart()}`);
	}

	execSync(
		`oxfmt --config .oxfmtrc.json ${[...outputs.keys()].map((path) => `"${path}"`).join(' ')}`,
		{
			cwd: ROOT,
			stdio: 'inherit',
		},
	);

	const hash = createHash('sha256');
	for (const path of [...outputs.keys()].sort()) {
		hash.update(normalizeForHash(readFileSync(path, 'utf8')));
	}

	const clientVersion = JSON.parse(readFileSync(join(CLIENT, 'package.json'), 'utf8')).version;
	const version = `${clientVersion}-${hash.digest('hex')}`;

	writeManifest(version, entries);

	execSync(`oxfmt --config .oxfmtrc.json "${join(ROOT, 'packages', 'api', 'package.json')}"`, {
		cwd: ROOT,
		stdio: 'inherit',
	});

	const duration = (performance.now() - start).toFixed(2);

	logger.success(`Generated plugin SDK v${version} in ${duration}ms`);
}

if (import.meta.main) {
	generate().catch((error) => {
		logger.error('Failed to generate plugin SDK:', error);
		process.exit(1);
	});
}
