// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT

export type { UnboundAsset } from './_internal';
declare const _default: {
	assets: Map<number, UnboundAsset>;
	find: typeof find;
	getByName: typeof getByName;
	getByID: typeof getByID;
	getIDByName: typeof getIDByName;
	getAll: typeof getAll;
	Icons: Record<string, number | undefined>;
};
/** Proxy resolving any property name to its asset id via {@link getIDByName}. */
export declare const Icons: Record<string, number | undefined>;
/** Map of discovered asset ids to their resolved {@link UnboundAsset} record. */
export declare const assets: Map<number, UnboundAsset>;
/**
 * @description Finds the first known asset matching the given predicate.
 * @param filter Predicate run against each asset.
 * @returns The matched {@link UnboundAsset}, or `undefined` if none match.
 */
export declare function find(filter: (asset: UnboundAsset) => boolean): UnboundAsset | undefined;
/**
 * @description Returns every known asset.
 * @returns An array of all registered {@link UnboundAsset} records.
 */
export declare function getAll(): UnboundAsset[];
/**
 * @description Looks up a known asset by its id.
 * @param id The asset id to look up.
 * @returns The matched {@link UnboundAsset}, or `undefined` if none is registered for that id.
 */
export declare function getByID(id: number): UnboundAsset | undefined;
/**
 * @description Finds a known asset by its name and type.
 * @param name The asset name to match.
 * @param type The asset type to match.
 * @returns The matched {@link UnboundAsset}, or `undefined` if none match.
 */
export declare function getByName(name: string, type?: 'svg' | 'png'): UnboundAsset | undefined;
/**
 * @description Looks up a known asset's id by its name and type.
 * @param name The asset name to match.
 * @param type The asset type to match.
 * @returns The matched asset's id, or `undefined` if none match.
 */
export declare function getIDByName(name: string, type?: 'svg' | 'png'): number | undefined;
export { _default as default };
