// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT

declare const _default: {
	Documents: string;
	read: typeof read;
	write: typeof write;
	rm: typeof rm;
	exists: typeof exists;
};
/** Absolute path to the platform's documents directory. */
export declare const Documents: string;
/**
 * @description Checks whether a file exists, resolving relative paths against {@link Documents}.
 * @param path The file path to check, relative to {@link Documents} unless `inDocuments` is `false`.
 * @param inDocuments Whether to resolve `path` relative to {@link Documents}.
 * @returns A promise resolving to whether the file exists.
 */
export declare function exists(path: string, inDocuments?: boolean): Promise<boolean>;
/**
 * @description Reads a file's contents, resolving relative paths against {@link Documents}.
 * @param path The file path to read, relative to {@link Documents} unless `inDocuments` is `false`.
 * @param encoding The encoding to read the file with.
 * @param inDocuments Whether to resolve `path` relative to {@link Documents}.
 * @returns A promise resolving to the file's contents.
 */
export declare function read(
	path: string,
	encoding?: DCDFileManagerEncoding,
	inDocuments?: boolean,
): Promise<string>;
/**
 * @description Removes a file within {@link Documents}.
 * @param path The file path to remove, relative to {@link Documents}.
 * @returns A promise resolving to whether the file was removed.
 */
export declare function rm(path: string): Promise<boolean>;
/**
 * @description Writes content to a file within {@link Documents}.
 * @param path The file path to write to, relative to {@link Documents}.
 * @param content The content to write.
 * @param encoding The encoding to write the file with.
 * @returns A promise resolving once the file is written.
 */
export declare function write(
	path: string,
	content: string,
	encoding?: DCDFileManagerEncoding,
): Promise<string>;
/** The text encodings accepted by the native `DCDFileManager` read/write operations. */
export type DCDFileManagerEncoding = 'utf-8' | 'utf8' | 'base64';

export { _default as default };
