// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT

import { ComponentType, ReactNode } from 'react';
import {
	ImageSourcePropType,
	ImageStyle,
	StyleProp,
	TextInputProps as RNTextInputProps,
	TextStyle,
	ViewProps,
	ViewStyle,
} from 'react-native';

declare const THEME_FLAG_KEYS: readonly [
	'MOBILE_DARK_GRADIENT_THEME_ENABLED',
	'MOBILE_LIGHT_GRADIENT_THEME_ENABLED',
	'REDUCED_CONTRAST_ENABLED',
	'INCREASED_CONTRAST_ENABLED',
	'REDUCE_SATURATION_ENABLED',
];
declare const TRANSITION_STATE_KEYS: readonly ['MOUNTED', 'ENTERED', 'YEETED'];
declare global {
	/** The raw `UnboundNative` JSI bridge the tweak installs directly on the JS global. */
	type UnboundNativeModule = {
		// Utilities
		getDeviceModel(): string;
		getiOSVersionString(): string;
		isJailbroken(): boolean;
		isSystemApp(): Promise<boolean>;
		isVerifiedBuild(): boolean;
		isAppStoreApp(): boolean;
		isTestFlightApp(): boolean;
		isTrollStoreApp(): boolean;
		isLiveContainerApp(): boolean;
		getTrollStoreVariant(): string;
		getApplicationEntitlements(): unknown;
		getAppSource(): string;
		getEntitlementsAsPlist(): string;
		showToolboxMenu(): void;
		// Plugin API
		showNotification(
			title: string,
			content: string,
			scheduledTime: number,
			sound: boolean,
			notificationId: string,
		): void;
		playPiPVideo(videoURL: string): void;
		// Chat UI
		setAvatarCornerRadius(radius: number): void;
		resetAvatarCornerRadius(): void;
		getAvatarCornerRadius(): number;
		setMessageBubblesEnabled(
			enabled: boolean,
			lightColor: ColorString | null,
			darkColor: ColorString | null,
		): void;
		setMessageBubbleColors(lightColor: ColorString, darkColor: ColorString): void;
		getMessageBubbleLightColor(): ColorString;
		getMessageBubbleDarkColor(): ColorString;
		getMessageBubblesEnabled(): boolean;
		getMessageBubbleCornerRadius(): number;
		setMessageBubbleCornerRadius(radius: number): void;
		resetMessageBubbles(): void;
	};
	/**
	 * Build-time token, replaced with a boolean literal by the build's `transform.define`. Folds at
	 * the module-graph level so `if ($$DEV$$)` branches (and any imports inside them) are dead-code
	 * eliminated from production bundles entirely. Use it (not a runtime check) to gate dev-only code.
	 */
	var $$DEV$$: boolean;
	/** The raw `UnboundNative` JSI bridge, installed on the global by the platform loader. */
	var UnboundNative: UnboundNativeModule | undefined;
	var React: typeof import('react');
	var ReactNative: typeof import('react-native');

	interface Window {}
}
/** A loaded addon entity: its runtime state, instance, source bundle, and {@link AddonManifest}. */
export interface Addon {
	started: boolean;
	instance: any;
	id: string;
	failed: boolean;
	data: AddonManifest;
	bundle: string;
}
/** The manifest describing an addon's metadata, entry point, and source. */
export interface AddonManifest {
	id: string;
	/** The addon kind this manifest describes; used to validate installs. */
	type?: 'plugin' | 'theme' | 'icon-pack' | 'font';
	name: string;
	description: string;
	authors: AddonAuthor[];
	icon:
		| (string & {})
		| {
				uri: string;
		  };
	updates: string;
	main: string;
	version: string;
	folder: string;
	path: string;
	url: string;
}
/** The native module used to register and resolve {@link DiscordAsset}s by id. */
export interface AssetsModule {
	registerAsset: (asset: DiscordAsset) => number;
	getAssetByID: (id: number) => DiscordAsset | null;
	[key: PropertyKey]: any;
}
export interface ButtonProps {
	text?: string;
	textElement?: ReactNode;
	variant?: ButtonVariant;
	size?: ButtonSize;
	loading?: boolean;
	disabled?: boolean;
	icon?: ReactNode | number;
	iconPosition?: 'start' | 'end';
	grow?: boolean;
	shrink?: boolean;
	shiny?: boolean;
	textVariant?: TextVariant;
	style?: StyleProp<ViewStyle>;
	accessibilityLabel?: string;
	onPress?: Fn<void>;
	onPressIn?: Fn<void>;
	onPressOut?: Fn<void>;
}
export interface CardProps extends ViewProps {
	variant?: LiteralUnion<'primary' | 'secondary' | 'muted' | 'transparent'>;
	border?: LiteralUnion<'none' | 'subtle' | 'strong'>;
	shadow?: LiteralUnion<'none' | 'low' | 'medium' | 'high' | 'border'>;
	radius?: number;
	start?: boolean;
	end?: boolean;
	children?: ReactNode;
}
export interface CheckboxProps {
	label?: ReactNode;
	description?: ReactNode;
	checked: boolean;
	required?: boolean;
	accessibilityRole?: string;
	accessibilityState?: Record<string, any>;
	onToggle: Fn<void>;
}
/**
 * The Discord mobile design system. This is the single metro module keyed by
 * `createStyles` / `dismissAlerts` / `ContextMenu` (aliased `Design` on the v3 branch). It is
 * intentionally left open: every listed member is precisely typed, and the index signature keeps
 * the rest (and anything Discord adds in a future build) accessible as `any` without a change here.
 *
 * See `DESIGN.md` at the repo root for the full catalogue.
 */
export interface DesignModule {
	createStyles: CreateStyles;
	TextStyleSheet: Record<TextVariant, TextStyle>;
	Text: ComponentType<TextProps>;
	Heading: ComponentType<TextProps>;
	TableRow: TableRowComponent;
	TableSwitchRow: ComponentType<TableSwitchRowProps>;
	TableCheckboxRow: ComponentType<TableCheckboxRowProps>;
	TableRadioRow: ComponentType<TableRadioRowProps>;
	TableRowGroup: ComponentType<TableRowGroupProps>;
	TableRowGroupTitle: ComponentType<TableRowGroupTitleProps>;
	TableRowIcon: ComponentType<TableRowIconProps>;
	RowButton: ComponentType<RowButtonProps>;
	RowGroup: ComponentType<ViewProps>;
	Button: ButtonComponent;
	IconButton: ComponentType<IconButtonProps>;
	ImageButton: ComponentType<ViewProps>;
	FloatingActionButton: ComponentType<FloatingActionButtonProps>;
	TextInput: ComponentType<TextInputProps>;
	TextField: ComponentType<TextFieldProps>;
	TextArea: ComponentType<TextAreaProps>;
	TextAreaField: ComponentType<TextAreaProps>;
	SearchField: ComponentType<Omit<TextFieldProps, 'leadingIcon'>>;
	GhostInput: ComponentType<GhostInputProps>;
	SplitTextInput: ComponentType<SplitTextInputProps>;
	Slider: ComponentType<SliderProps>;
	Checkbox: ComponentType<CheckboxProps>;
	SegmentedControl: ComponentType<SegmentedControlProps>;
	Stack: ComponentType<StackProps>;
	Card: ComponentType<CardProps>;
	openAlert: Fn<void>;
	dismissAlert: (key: string) => void;
	dismissAlerts: Fn<void>;
	showConfirmModal: Fn;
	showSimpleActionSheet: Fn;
	hideContextMenu: Fn<void>;
	useNavigation: <T = any>() => Navigation$1<T>;
	setColorOpacity: (color: string, opacity: number) => string;
	darkenColor: (color: string, amount: number) => string;
	brightenColor: (color: string, amount: number) => string;
	getContrastingColor: (color: string) => string;
	TransitionStates: EnumLike<typeof TRANSITION_STATE_KEYS>;
	ThemeContextFlags: EnumLike<typeof THEME_FLAG_KEYS>;
	WCAGContrastRatios: Record<'NonText' | 'Text' | 'HighContrastText', number>;
	[key: PropertyKey]: any;
}
/** An asset registered with Discord's packager (its metadata and dimensions). */
export interface DiscordAsset {
	__packager_asset?: boolean;
	name: string;
	httpServerLocation?: string;
	width: number;
	height: number;
	scales: number[];
	hash: string;
	type: string;
	[key: PropertyKey]: any;
}
/** `FloatingActionButton`: a single-icon FAB, typically pinned to a screen corner. */
export interface FloatingActionButtonProps {
	icon?: ReactNode | number;
	style?: StyleProp<ViewStyle>;
	onPress?: Fn<void>;
}
/** `GhostInput`: a borderless field bridging to the `useTextField` hook. */
export interface GhostInputProps extends TextFieldProps {
	isCentered?: boolean;
	containerStyle?: StyleProp<ViewStyle>;
}
export interface IconButtonProps {
	icon?: ReactNode | number;
	variant?: ButtonVariant;
	size?: ButtonSize;
	loading?: boolean;
	disabled?: boolean;
	label?: string;
	accessibilityLabel?: string;
	style?: StyleProp<ViewStyle>;
	onPress?: Fn<void>;
}
/** {@link ToastOptions} enriched with the fields the store tracks internally. */
export interface InternalToastOptions extends ToastOptions {
	id: string;
	closing?: boolean;
	date?: number;
}
export interface RowButtonProps {
	label?: ReactNode;
	icon?: ReactNode;
	arrow?: boolean;
	disabled?: boolean;
	variant?: LiteralUnion<'primary' | 'secondary'>;
	onPress?: Fn<void>;
}
export interface SegmentedControlProps {
	/** The controller returned by `useSegmentedControlState`. */
	state: SegmentedControlState;
	/** @default 'default' */
	variant?: LiteralUnion<'default'>;
	keyboardShouldPersistTaps?: boolean | 'always' | 'never' | 'handled';
}
/** The state controller a `SegmentedControl` is driven by. */
export interface SegmentedControlState {
	activeIndex: number;
	items: any[];
	setActiveIndex: (index: number) => void;
}
/** A registered Unbound settings entry, mirroring Discord's `SETTING_RENDERER_CONFIG` route shape. */
export interface SettingsEntry {
	type: 'route';
	key: string;
	useTitle: () => string;
	parent: string | null;
	section?: string;
	excludeFromDisplay?: boolean;
	IconComponent?: ComponentType<any>;
	screen: SettingsScreen;
}
/** The screen descriptor a settings route entry renders. */
export interface SettingsScreen {
	route: string;
	getComponent: () => ComponentType<any>;
}
/**
 * The DS `Slider`. It reads only `startIcon` / `endIcon` / `style` / `onValueChange` / `step`; the
 * remaining slider props (`value`, bounds, tint colours) are spread onto the underlying RN slider.
 */
export interface SliderProps {
	value?: number;
	defaultValue?: number;
	minimumValue?: number;
	maximumValue?: number;
	step?: number;
	disabled?: boolean;
	inverted?: boolean;
	tapToSeek?: boolean;
	lowerLimit?: number;
	upperLimit?: number;
	startIcon?: ReactNode;
	endIcon?: ReactNode;
	valueLabel?: ReactNode;
	minimumTrackTintColor?: string;
	maximumTrackTintColor?: string;
	style?: StyleProp<ViewStyle>;
	onValueChange?: (value: number) => void;
	onSlidingStart?: (value: number) => void;
	onSlidingComplete?: (value: number) => void;
}
/** `SplitTextInput` / `SplitTextField`: a segmented input (e.g. verification codes). */
export interface SplitTextInputProps extends TextFieldProps {
	isRound?: boolean;
	leadingText?: string;
	leadingPressableProps?: Record<string, any>;
}
export interface StackProps extends ViewProps {
	spacing?: number;
	direction?: 'horizontal' | 'vertical';
	align?: 'start' | 'center' | 'end' | 'stretch';
	justify?: 'start' | 'center' | 'end' | 'between' | 'around';
	children?: ReactNode;
}
export interface TableCheckboxRowProps {
	label?: ReactNode;
	subLabel?: ReactNode;
	checked: boolean;
	disabled?: boolean;
	accessibilityHint?: string;
	onPress: Fn<void>;
}
export interface TableRadioRowProps {
	label?: ReactNode;
	subLabel?: ReactNode;
	value: any;
	disabled?: boolean;
	accessibilityHint?: string;
	legacyCompat?: boolean;
}
export interface TableRowGroupProps {
	title?: string;
	description?: string;
	helperText?: string;
	hasIcons?: boolean;
	hasTrailingText?: boolean;
	accessibilityRole?: string;
	accessibilityLabel?: string;
	children?: ReactNode;
}
export interface TableRowGroupTitleProps {
	title: string;
}
export interface TableRowIconProps {
	source?: number;
	IconComponent?: ComponentType<any>;
	variant?: LiteralUnion<'default' | 'danger' | 'blurple'>;
}
export interface TableRowProps {
	label?: ReactNode;
	subLabel?: ReactNode;
	icon?: ReactNode;
	trailing?: ReactNode;
	arrow?: boolean;
	disabled?: boolean;
	/** Rounds the top corners; set on the first row of a manually laid-out group. */
	start?: boolean;
	/** Rounds the bottom corners; set on the last row of a manually laid-out group. */
	end?: boolean;
	labelLineClamp?: number;
	subLabelLineClamp?: number;
	variant?: LiteralUnion<'default' | 'danger'>;
	draggable?: boolean;
	onPress?: Fn<void>;
	children?: ReactNode;
}
export interface TableSwitchRowProps {
	label?: ReactNode;
	subLabel?: ReactNode;
	icon?: ReactNode;
	trailing?: ReactNode;
	value: boolean;
	disabled?: boolean;
	accessibilityHint?: string;
	variant?: LiteralUnion<'default'>;
	onValueChange: (value: boolean) => void;
}
/** `TextArea` extends the field family with a character limit. */
export interface TextAreaProps extends TextFieldProps {
	maxLength?: number;
}
/**
 * The redesign `TextField` and its siblings (`TextArea`, `SearchField`, `GhostInput`,
 * `SplitTextInput`). This is where the `size` / `status` / `isClearable` / `leadingIcon` chrome
 * actually lives, unlike {@link TextInputProps}. `onChange` receives the string value.
 */
export interface TextFieldProps {
	value?: string;
	defaultValue?: string;
	placeholder?: string;
	autoFocus?: boolean;
	size?: InputSize;
	/** @default 'default' */
	status?: InputStatus;
	isClearable?: boolean;
	isDisabled?: boolean;
	isRound?: boolean;
	grow?: boolean;
	leadingIcon?: IconSlot;
	trailingIcon?: IconSlot;
	leadingText?: string;
	trailingText?: string;
	leadingPressableProps?: Record<string, any>;
	trailingPressableProps?: Record<string, any>;
	secureTextEntry?: boolean;
	keyboardType?: RNTextInputProps['keyboardType'];
	autoComplete?: RNTextInputProps['autoComplete'];
	returnKeyType?: RNTextInputProps['returnKeyType'];
	maxLength?: number;
	enableAndroidSanitizedInputWorkaround?: boolean;
	style?: StyleProp<ViewStyle>;
	inputStyle?: StyleProp<TextStyle>;
	children?: ReactNode;
	onChange?: (value: string) => void;
	onClear?: Fn<void>;
	onFocus?: RNTextInputProps['onFocus'];
	onBlur?: RNTextInputProps['onBlur'];
}
/**
 * Discord's own form-style `TextInput` (`TextInput.native`), not React Native's. Its `onChange`
 * receives the raw string value, not an event. These are the props it reads verbatim off its props
 * object; every other prop is collected and spread onto the underlying native input via
 * {@link TextInputPassthrough}.
 */
export interface TextInputProps extends TextInputPassthrough {
	value?: string;
	/** @default '' */
	placeholder?: string;
	/** Field label rendered above the input. @default '' */
	title?: string;
	/** @default '' */
	helpText?: string;
	/** Error message, or `true` to show the error state without text. */
	error?: string | boolean;
	/** @default false */
	disabled?: boolean;
	/** @default false */
	multiline?: boolean;
	/** @default 1 */
	numberOfLines?: number;
	/** @default false */
	autoFocus?: boolean;
	/** @default false */
	secureTextEntry?: boolean;
	keyboardType?: RNTextInputProps['keyboardType'];
	keyboardAppearance?: RNTextInputProps['keyboardAppearance'];
	autoCapitalize?: RNTextInputProps['autoCapitalize'];
	autoCorrect?: boolean;
	/** iOS clear-button mode; forwarded to the native input. */
	clearButtonVisibility?: LiteralUnion<'never' | 'always' | 'unless-editing' | 'while-editing'>;
	showBorder?: boolean;
	/** @default false */
	showCharactersRemaining?: boolean;
	inputTextStyle?: StyleProp<TextStyle>;
	style?: StyleProp<ViewStyle>;
	/** @default false */
	enableAndroidSanitizedInputWorkaround?: boolean;
	/** Switches between the legacy and redesign render paths. @default true */
	allowRedesignTextInput?: boolean;
	onChange?: (value: string) => void;
}
export interface TextProps extends ViewProps {
	children?: ReactNode;
	variant?: TextVariant;
	color?: LiteralUnion<'text-normal' | 'text-muted' | 'header-primary' | 'header-secondary'>;
	style?: StyleProp<TextStyle>;
	lineClamp?: number;
	ellipsizeMode?: 'head' | 'middle' | 'tail' | 'clip';
	tabularNumbers?: boolean;
	animated?: boolean;
	numberOfLines?: number;
	allowFontScaling?: boolean;
}
/** A theme's semantic and raw colour definitions plus optional background. */
export interface Theme {
	semantic: Record<PropertyKey, ThemeSemanticColor>;
	raw: Record<PropertyKey, string>;
	type: 'midnight' | 'darker' | 'light';
	background?: {
		blur?: number;
		opacity?: number;
		url: string;
	};
}
/** A button rendered inside a toast. */
export interface ToastButton {
	variant?: 'primary' | 'secondary' | 'tertiary';
	size?: 'sm' | 'md' | 'lg' | 'xl' | '2xl';
	iconPosition?: 'start' | 'end';
	content: string;
	icon?: number;
	onPress: Fn;
}
/** A handle returned when showing a toast, used to update or close it. */
export interface ToastHandle {
	update: (options: Partial<ToastOptions>) => void;
	close: () => void;
}
/** Options accepted when showing a toast. */
export interface ToastOptions {
	title?: string | ComponentType;
	content?: string;
	duration?: number;
	onTimeout?: Fn;
	icon?: string | number | ImageSourcePropType;
	id?: string;
	buttons?: ToastButton[];
	tintedIcon?: boolean;
}
/** State and actions of the toast store. */
export interface ToastStoreState {
	toasts: Record<string, InternalToastOptions>;
	addToast: (options: InternalToastOptions) => ToastHandle;
	updateToastWithOptions: (id: string, options: Partial<InternalToastOptions>) => void;
}
export interface TrailingTextProps {
	text: string;
}
/** The author of an addon: a display name and a numeric user id. */
export type AddonAuthor = {
	name: string;
	id: `${number}`;
};
/** An addon referenced either by its id string or the {@link Addon} entity itself. */
export type AddonResolveable = string | Addon;
/** An object of shape `T` widened with an arbitrary string/number/symbol index. */
export type AnyProps<T extends Record<PropertyKey, any> = Record<PropertyKey, any>> = T &
	Record<PropertyKey, any>;
/** `Button` with its attached `Icon` static. */
export type ButtonComponent = ComponentType<ButtonProps> & {
	Icon: ComponentType<TableRowIconProps>;
};
export type ButtonSize = LiteralUnion<'sm' | 'md' | 'lg'>;
export type ButtonVariant = LiteralUnion<
	'primary' | 'secondary' | 'tertiary' | 'destructive' | 'active' | 'expressive'
>;
/** Any supported colour string: a {@link HexColor} or {@link RgbaColor}. */
export type ColorString = HexColor | RgbaColor;
/**
 * The style factory. Accepts a spec object (or a function returning one) and returns a hook. The
 * hook subscribes to the theme context and lazily resolves each key on access, so it must be called
 * inside a component body: `const styles = useStyles();`.
 */
export type CreateStyles = <T extends StyleSheetSpec>(
	styles: StyleSheetSpecOrFactory<T>,
) => Fn<ResolvedStyles<T>>;
/** Discord ships numeric enums as bidirectional maps; this models both directions. */
export type EnumLike<K extends readonly string[]> = {
	[P in K[number]]: number;
} & {
	[n: number]: K[number];
};
/** The set of all falsy values. */
export type Falsy = false | 0 | '' | null | undefined;
/** Any function: accepts any arguments and returns `T`. */
export type Fn<T = any> = (...args: any) => T;
/** A custom font the native loader has registered, as injected on `window.UNBOUND_FONTS`. */
export type FontDescriptor = {
	name: string;
	file: string;
	path: string;
};
/** A font managed by the Fonts manager: currently identical to its {@link FontDescriptor}. */
export type FontEntity = FontDescriptor;
/** A hexadecimal colour string prefixed with `#`. */
export type HexColor = `#${string}`;
/** A loaded icon pack: its bundle marker and {@link IconPackManifest}. */
export type IconPack = {
	bundle: string;
	manifest: IconPackManifest;
};
/** An icon pack's manifest: an {@link AddonManifest} tagged with its source kind. */
export type IconPackManifest = AddonManifest & {
	type: 'icon-pack';
	source: 'github' | 'other';
};
/** Icon slot: a rendered node, a component, or a render function. */
export type IconSlot = ReactNode | ComponentType<any> | Fn<ReactNode>;
/** Input sizing, shared by the whole `TextField`/`Input` family. */
export type InputSize = LiteralUnion<'sm' | 'md' | 'lg'>;
/** Input status. `focused` is an internal state and is not user-settable. */
export type InputStatus = LiteralUnion<'default' | 'error'>;
/**
 * A string union that keeps `T`'s literals for autocomplete while still accepting any other string.
 * Use this for Discord's open-ended enums (typography variants, colour tokens, sizes) so newly added
 * values keep type-checking without an update here.
 */
export type LiteralUnion<T extends string> = T | (string & {});
/** An {@link Addon} whose instance is a {@link Plugin}. */
export type PluginEntity = Addon & {
	instance: Plugin$1 | null;
};
/** The result of a predicate: any {@link Truthy} or {@link Falsy} value. */
export type PredicateResult = Truthy | Falsy;
/** Any function returning a promise (`T` defaults to `Promise<any>`). */
export type PromiseFn<T = Promise<any>> = (...args: any) => T;
/** Resolves each key of a {@link StyleSheetSpec} to the concrete RN style type it produced. */
export type ResolvedStyles<T extends StyleSheetSpec> = {
	[K in keyof T]: T[K] extends ImageStyle
		? ImageStyle
		: T[K] extends TextStyle
			? TextStyle
			: ViewStyle;
};
/** An `rgba(...)` colour string. */
export type RgbaColor = `rgba(${string})`;
/** A stylesheet spec: each key maps to a view, text, or image style. */
export type StyleSheetSpec = Record<
	string,
	ViewStyle | TextStyle | ImageStyle | Record<PropertyKey, any>
>;
/** A stylesheet spec, or a function producing one (Discord accepts both forms). */
export type StyleSheetSpecOrFactory<T extends StyleSheetSpec> = T | ((...args: any[]) => T);
/** `TableRow` with its attached statics (`Icon`, `Arrow`, `TrailingText`). */
export type TableRowComponent = ComponentType<TableRowProps> & {
	Icon: ComponentType<TableRowIconProps>;
	Arrow: ComponentType<ViewProps>;
	TrailingText: ComponentType<TrailingTextProps>;
};
/**
 * Native `TextInput` props forwarded through `TextInput`. Everything the DS component does not read
 * itself (`maxLength`, `selectionColor`, `onFocus`, …) is spread onto the underlying native input,
 * so it accepts the RN surface too, minus the members `TextInput` overrides with its own semantics.
 */
export type TextInputPassthrough = Omit<
	RNTextInputProps,
	| 'value'
	| 'placeholder'
	| 'multiline'
	| 'numberOfLines'
	| 'autoFocus'
	| 'secureTextEntry'
	| 'keyboardType'
	| 'keyboardAppearance'
	| 'autoCapitalize'
	| 'autoCorrect'
	| 'style'
	| 'onChange'
>;
/** Every typography variant Discord ships in `TextStyleSheet`, kept open for new ones. */
export type TextVariant = LiteralUnion<
	| `heading-${'sm' | 'md' | 'lg' | 'xl' | 'xxl'}/${TextWeight | 'extrabold'}`
	| `experimental/heading-${'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'xxl'}/${'semibold' | 'bold'}`
	| `heading-deprecated-12/${TextWeight | 'extrabold'}`
	| `redesign/heading-18/${'medium' | 'semibold' | 'bold'}`
	| `text-${'xxs' | 'xs' | 'sm' | 'md' | 'lg'}/${TextWeight}`
	| `redesign/message-preview/${TextWeight}`
	| `redesign/channel-title/${TextWeight}`
	| `experimental/body-${'xs' | 'sm' | 'md' | 'lg'}/${'normal' | 'medium'}`
	| `experimental/meta/${'normal' | 'medium'}`
	| `experimental/label-${'xs' | 'sm' | 'md' | 'lg'}/${'medium' | 'semibold'}`
	| `experimental/mono-${'sm' | 'md'}/${'normal' | 'bold'}`
	| `display-${'sm' | 'md' | 'lg'}`
	| `experimental/display-${'xs' | 'sm' | 'md' | 'lg'}`
	| 'eyebrow'
>;
/** The four common font weights used across typography variants. */
export type TextWeight = 'normal' | 'medium' | 'semibold' | 'bold';
/** An {@link Addon} whose instance is a {@link Theme}, tracking its registration state. */
export type ThemeEntity = Addon & {
	registered: boolean;
	instance: Theme | null;
};
/** A single semantic colour definition in a {@link Theme}. */
export type ThemeSemanticColor = {
	type: 'color' | 'raw';
	value: string;
	opacity?: number;
};
/** `TransitionStates`: MOUNTED = 0, ENTERED = 1, YEETED = 2. */
export type TransitionState = 'MOUNTED' | 'ENTERED' | 'YEETED';
/** The set of all truthy values. */
export type Truthy = true | number | string | object | symbol | bigint;
/** A {@link DiscordAsset} extended with Unbound's icon-pack overrides. */
export type UnboundAsset = DiscordAsset & {
	iconPackPath?: string;
	iconPackScale?: number;
};
/** Widens a literal type to its primitive base (e.g. `'a'` to `string`, `1` to `number`). */
export type Widen<T> = T extends number
	? number
	: T extends string
		? string
		: T extends boolean
			? boolean
			: T;
interface Navigation$1<T = any> {
	push: (route: string, params?: T) => void;
	pop: () => void;
	navigate: (route: string, params?: T) => void;
	goBack: () => void;
	setOptions: (options: Record<string, any>) => void;
	addListener: (event: string, callback: Fn) => Fn<void>;
	[key: string]: any;
}
/** The lifecycle and settings contract implemented by a plugin. */
interface Plugin$1 {
	start?(): void;
	stop?(): void;
	getSettingsPanel?(): ReactNode;
}

export { Navigation$1 as Navigation, Plugin$1 as Plugin };

export {};

export interface UnboundGlobal {
	settings: typeof import('./settings.d.ts');
	patcher: typeof import('./patcher.d.ts');
	storage: typeof import('./storage.d.ts');
	assets: typeof import('./assets.d.ts');
	native: typeof import('./native.d.ts');
	toasts: typeof import('./toasts.d.ts');
	metro: typeof import('./metro/index.d.ts');
	i18n: typeof import('./i18n.d.ts');
	fs: typeof import('./fs.d.ts');
}

declare global {
	interface Window {
		unbound: UnboundGlobal;
	}

	const unbound: Window['unbound'];
}
