// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT

export type {
	Addon,
	AddonAuthor,
	AddonManifest,
	AddonResolveable,
	AnyProps,
	AssetsModule,
	ButtonComponent,
	ButtonProps,
	ButtonSize,
	ButtonVariant,
	CardProps,
	CheckboxProps,
	ColorString,
	CreateStyles,
	DesignModule,
	DiscordAsset,
	EnumLike,
	Falsy,
	FloatingActionButtonProps,
	Fn,
	FontDescriptor,
	FontEntity,
	GhostInputProps,
	HexColor,
	IconButtonProps,
	IconPack,
	IconPackManifest,
	IconSlot,
	InputSize,
	InputStatus,
	InternalToastOptions,
	LiteralUnion,
	Navigation$1,
	Plugin$1,
	PluginEntity,
	PredicateResult,
	PromiseFn,
	ResolvedStyles,
	RgbaColor,
	RowButtonProps,
	SegmentedControlProps,
	SegmentedControlState,
	SettingsEntry,
	SettingsScreen,
	SliderProps,
	SplitTextInputProps,
	StackProps,
	StyleSheetSpec,
	StyleSheetSpecOrFactory,
	THEME_FLAG_KEYS,
	TRANSITION_STATE_KEYS,
	TableCheckboxRowProps,
	TableRadioRowProps,
	TableRowComponent,
	TableRowGroupProps,
	TableRowGroupTitleProps,
	TableRowIconProps,
	TableRowProps,
	TableSwitchRowProps,
	TextAreaProps,
	TextFieldProps,
	TextInputPassthrough,
	TextInputProps,
	TextProps,
	TextVariant,
	TextWeight,
	Theme,
	ThemeEntity,
	ThemeSemanticColor,
	ToastButton,
	ToastHandle,
	ToastOptions,
	ToastStoreState,
	TrailingTextProps,
	TransitionState,
	Truthy,
	UnboundAsset,
	Widen,
} from './utilities';

import { ComponentType, ReactNode } from 'react';
import {
	ImageSourcePropType,
	ImageStyle,
	StyleProp,
	TextInputProps as RNTextInputProps,
	TextStyle,
	ViewProps,
	ViewStyle,
} from 'react-native';

declare global {
	/** The raw `UnboundNative` JSI bridge the tweak installs directly on the JS global. */
	type UnboundNativeModule = {
		// Utilities
		getDeviceModel(): string;
		getiOSVersionString(): string;
		isJailbroken(): boolean;
		isSystemApp(): Promise<boolean>;
		isVerifiedBuild(): boolean;
		isAppStoreApp(): boolean;
		isTestFlightApp(): boolean;
		isTrollStoreApp(): boolean;
		isLiveContainerApp(): boolean;
		getTrollStoreVariant(): string;
		getApplicationEntitlements(): unknown;
		getAppSource(): string;
		getEntitlementsAsPlist(): string;
		showToolboxMenu(): void;
		// Plugin API
		showNotification(
			title: string,
			content: string,
			scheduledTime: number,
			sound: boolean,
			notificationId: string,
		): void;
		playPiPVideo(videoURL: string): void;
		// Chat UI
		setAvatarCornerRadius(radius: number): void;
		resetAvatarCornerRadius(): void;
		getAvatarCornerRadius(): number;
		setMessageBubblesEnabled(
			enabled: boolean,
			lightColor: ColorString | null,
			darkColor: ColorString | null,
		): void;
		setMessageBubbleColors(lightColor: ColorString, darkColor: ColorString): void;
		getMessageBubbleLightColor(): ColorString;
		getMessageBubbleDarkColor(): ColorString;
		getMessageBubblesEnabled(): boolean;
		getMessageBubbleCornerRadius(): number;
		setMessageBubbleCornerRadius(radius: number): void;
		resetMessageBubbles(): void;
	};
	/**
	 * Build-time token, replaced with a boolean literal by the build's `transform.define`. Folds at
	 * the module-graph level so `if ($$DEV$$)` branches (and any imports inside them) are dead-code
	 * eliminated from production bundles entirely. Use it (not a runtime check) to gate dev-only code.
	 */
	var $$DEV$$: boolean;
	/** The raw `UnboundNative` JSI bridge, installed on the global by the platform loader. */
	var UnboundNative: UnboundNativeModule | undefined;
	var React: typeof import('react');
	var ReactNative: typeof import('react-native');

	interface Window {}
}

export interface UnboundGlobal {
	assets: typeof import('./assets.d.ts');
	fs: typeof import('./fs.d.ts');
	i18n: typeof import('./i18n.d.ts');
	metro: typeof import('./metro/index.d.ts');
	native: typeof import('./native.d.ts');
	patcher: typeof import('./patcher.d.ts');
	settings: typeof import('./settings.d.ts');
	storage: typeof import('./storage.d.ts');
	toasts: typeof import('./toasts.d.ts');
}

declare global {
	interface Window {
		unbound: UnboundGlobal;
	}

	const unbound: Window['unbound'];
}
