// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT

export type {
	Addon,
	AddonAuthor,
	AddonManifest,
	AddonResolveable,
	AssetsModule,
	ButtonComponent,
	ButtonProps,
	ButtonSize,
	ButtonVariant,
	CardProps,
	CheckboxProps,
	CreateStyles,
	DesignModule,
	DiscordAsset,
	EnumLike,
	FloatingActionButtonProps,
	FontDescriptor,
	FontEntity,
	GhostInputProps,
	IconButtonProps,
	IconPack,
	IconPackManifest,
	IconSlot,
	InputSize,
	InputStatus,
	InternalToastOptions,
	NativeAssociationKey,
	NativeCallOptions,
	NativeClassHandle,
	NativeFFIBridge,
	NativeFFISignature,
	NativeFFIType,
	NativeFFITypeName,
	NativeFabricBridge,
	NativeFabricFrame,
	NativeFabricSize,
	NativeFabricSurface,
	NativeHandle,
	NativeHookContext,
	NativeHookHandlers,
	NativeHookOptions,
	NativeHookToken,
	NativeObjCBridge,
	NativeObjectHandle,
	NativePlatformApp,
	NativePlatformBridge,
	NativePlatformDevice,
	NativePluginBridge,
	NativePluginCapability,
	NativePluginError,
	NativePluginErrorCode,
	NativePointer,
	NativeStruct,
	NativeThreadPolicy,
	Navigation,
	Plugin,
	PluginContext,
	PluginEntity,
	ResolvedStyles,
	RowButtonProps,
	SegmentedControlProps,
	SegmentedControlState,
	SettingsEntry,
	SettingsScreen,
	SliderProps,
	SplitTextInputProps,
	StackProps,
	StyleSheetSpec,
	StyleSheetSpecOrFactory,
	SwitchProps,
	TableCheckboxRowProps,
	TableRadioRowProps,
	TableRowComponent,
	TableRowGroupProps,
	TableRowGroupTitleProps,
	TableRowIconProps,
	TableRowProps,
	TableSwitchRowProps,
	TextAreaProps,
	TextFieldProps,
	TextInputPassthrough,
	TextInputProps,
	TextProps,
	TextVariant,
	TextWeight,
	Theme,
	ThemeEntity,
	ThemeSemanticColor,
	ToastButton,
	ToastHandle,
	ToastOptions,
	ToastStoreState,
	TrailingTextProps,
	TransitionState,
	UnboundAsset,
} from './_internal';
import type { NativePlatformBridge } from './_internal';
declare global {
	/**
	 * Build-time token, replaced with a boolean literal by the build's `transform.define`. Folds at
	 * the module-graph level so `if ($$DEV$$)` branches (and any imports inside them) are dead-code
	 * eliminated from production bundles entirely. Use it (not a runtime check) to gate dev-only code.
	 */
	var $$DEV$$: boolean;
	var NativePlatform: NativePlatformBridge | undefined;
	var React: typeof import('react');
	var ReactNative: typeof import('react-native');

	interface Window {}
}

export interface UnboundGlobal {
	assets: typeof import('./assets.d.ts');
	fs: typeof import('./fs.d.ts');
	i18n: typeof import('./i18n.d.ts');
	metro: typeof import('./metro/index.d.ts');
	native: typeof import('./native.d.ts');
	patcher: typeof import('./patcher.d.ts');
	settings: typeof import('./settings.d.ts');
	storage: typeof import('./storage.d.ts');
	toasts: typeof import('./toasts.d.ts');
}

declare global {
	interface Window {
		unbound: UnboundGlobal;
	}

	const unbound: Window['unbound'];
}
