// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT

declare const _default: {
	Messages: Record<string, string>;
	format: typeof format;
	defineLocalizations: typeof defineLocalizations;
	init: typeof init;
	destroy: typeof destroy;
};
/** The core `Messages` proxy, resolving Unbound's own UI strings against the active Discord locale. */
export declare const Messages: Record<string, string>;
/**
 * @description Creates an isolated, in-memory `Messages`/`format` pair over an addon-supplied string table, sharing the active locale with core.
 * @param table The addon's string store, keyed by locale then message key.
 * @returns A `Messages` proxy and `format` function scoped to the supplied table.
 */
export declare function defineLocalizations(table: StringStore): Localizations;
/**
 * @description Drains every active locale-change subscription. Idempotent. Twin of {@link init}.
 */
export declare function destroy(): void;
/**
 * @description Formats a localized string, interpolating ICU `MessageFormat` placeholders.
 * @param key The message key to resolve and format.
 * @param vars The variables to interpolate into the message.
 * @returns The formatted string.
 */
export declare function format(key: string, vars?: FormatVars): string;
/**
 * @description Loads the fallback and active locales, then subscribes to Discord locale changes. Fire-and-forget; never blocks startup. Twin of {@link destroy}.
 * @returns A promise that resolves once the initial locales have been ensured and the subscription is wired.
 */
export declare function init(): Promise<void>;
export type FormatVars = Record<string, unknown>;
export type LocaleStrings = Record<string, string>;
export type Localizations = {
	Messages: Record<string, string>;
	format: (key: string, vars?: FormatVars) => string;
};
export type StringStore = Record<string, LocaleStrings>;

export { _default as default };
