// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT

import { ComponentType, ReactNode } from 'react';
import { ImageSourcePropType } from 'react-native';

declare class EventEmitter<
	EventMap extends DefaultEventMap = DefaultEventMap,
> implements IEventEmitter<EventMap> {
	events: {
		[eventName in keyof EventMap]?: TaskCollection<EventMap[eventName]>;
	};
	onceEvents: {
		[eventName in keyof EventMap]?: EventMap[eventName][] | EventMap[eventName];
	};
	boundFuncs: undefined | Map<Function, Function>;
	_symbolKeys: Set<symbol>;
	maxListeners: number;
	get _eventsCount(): number;
	emit: <EventKey extends keyof EventMap>(
		event: EventKey,
		...args: Parameters<EventMap[EventKey]>
	) => boolean;
	on: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => this;
	once: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => this;
	addListener: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
		argsNum?: ArgsNum<EventMap[EventKey]>,
	) => this;
	removeListener: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => this;
	hasListeners: <EventKey extends keyof EventMap = string>(event: EventKey) => boolean;
	prependListener: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => this;
	prependOnceListener: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => this;
	off: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => this;
	removeAllListeners: <EventKey extends keyof EventMap = string>(event?: EventKey) => this;
	setMaxListeners: (n: number) => this;
	getMaxListeners: () => number;
	listeners: <EventKey extends keyof EventMap = string>(event: EventKey) => EventMap[EventKey][];
	rawListeners: <EventKey extends keyof EventMap = string>(
		event: EventKey,
	) => EventMap[EventKey][];
	eventNames: () => Array<string | symbol>;
	listenerCount: <EventKey extends keyof EventMap = string>(type: EventKey) => number;
	addListenerBound: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
		bindTo?: any,
		argsNum?: ArgsNum<EventMap[EventKey]>,
	) => this;
	removeListenerBound: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => this;
}

declare class TaskCollection<
	Func extends (...args: any) => void,
	AwaitTasks extends true | false = false,
> {
	readonly awaitTasks: AwaitTasks;
	constructor(
		argsNum: ArgsNum<Func>,
		autoRebuild?: boolean,
		initialTasks?: Func[] | Func | null,
		awaitTasks?: AwaitTasks,
	);
	/** DO NOT CHANGE DIRECTLY */
	_tasks: Func[] | Func | null;
	/** cached */
	length: number;
	/** auto rebuild on first emit call; otherwise autorebuild on every change */
	firstEmitBuildStrategy: boolean;
	readonly argsNum: ArgsNum<Func>;
	autoRebuild: boolean;
	readonly growArgsNum: typeof growArgsNum;
	setAutoRebuild: typeof setAutoRebuild;
	call: (...args: Parameters<Func>) => AwaitTasks extends true ? Promise<void> : void;
	rebuild: () => void;
	push: (...func: Func[]) => void;
	/** remove last matched task from tasks */
	removeLast: (func: Func) => void;
	insert: (index: number, ...func: Func[]) => void;
	setTasks: (tasks: Func[]) => void;
	tasksAsArray: () => Func[];
	/** this autorebuilds */
	readonly clear: typeof clear;
	/** this autorebuilds */
	readonly fastClear: typeof fastClear;
}

declare const Assets: any;
declare const AsyncUsers: any;
declare const BundleInfo: BundleInfoType;
declare const BundleManager: DCDBundleManagerType;
declare const CACHE_KEY: unique symbol;
declare const Clipboard$1: any;
declare const Clyde: any;
declare const Commands: any;
declare const Constants: any;
declare const DeviceInfo: DeviceInfoType;
declare const Dispatcher: any;
declare const Documents: string;
declare const Flux: any;
declare const Gestures: any;
declare const Guilds: any;
declare const Icons$1: Record<string, number | undefined>;
declare const Invites: any;
declare const Linking: any;
declare const MarkdownParser: any;
declare const Messages$1: Record<string, string>;
declare const Messages: any;
declare const Moment: any;
declare const PATCH_SYMBOL: unique symbol;
declare const Profiles: any;
declare const REST: any;
declare const Radius: any;
declare const React$1: typeof import('react');
declare const ReactNative$1: typeof import('react-native');
declare const Reanimated: any;
declare const SVG: any;
declare const Screens: any;
declare const Theme$1: any;
declare const Theme$2: any;
declare const UnboundNative$1: UnboundNativeModule | undefined;
declare const Users: any;
declare const Util: any;
declare const assets: Map<number, UnboundAsset>;
declare const i18n: any;
declare const off$1: typeof removeListener$1;
declare const off: <EventKey extends keyof EventMap = string>(
	event: EventKey,
	listener: EventMap[EventKey],
) => EventEmitter<EventMap>;
declare const on$1: typeof addListener$1;
declare const on: <EventKey extends keyof EventMap = string>(
	event: EventKey,
	listener: EventMap[EventKey],
) => EventEmitter<EventMap>;
declare const patches: PatchedModule[];

declare enum PatchType {
	Before = 0,
	Instead = 1,
	After = 2,
}
declare function addListener$1(listener: (mdl: any, id: string) => void): () => boolean;
declare function addListener(
	predicate: (payload: SettingsPayload) => PredicateResult,
	callback: (payload: SettingsPayload) => void,
): () => EventEmitter<EventMap>;
declare function after<M extends PatchParent, P extends PropOf<M>>(
	parent: M,
	method: P,
	callback: PatchCallback<
		M[P] extends (...args: infer Args) => any ? Args : any[],
		M[P] extends (...args: any[]) => infer Res ? Res : any,
		unknown extends ThisParameterType<M[P]> ? M : ThisParameterType<M[P]>
	>,
	options?: PatchOptions,
): () => void;
declare function before<M extends PatchParent, P extends PropOf<M>>(
	parent: M,
	method: P,
	callback: PatchCallback<
		M[P] extends (...args: infer Args) => any ? Args : any[],
		M[P] extends (...args: any[]) => infer Res ? Res : any,
		unknown extends ThisParameterType<M[P]> ? M : ThisParameterType<M[P]>
	>,
	options?: PatchOptions,
): () => void;
declare function bulk(...items: MetroBulkItem[]): any[];
declare function byDisplayName(name: string): MetroFilter;
declare function byFilePath(path: string[]): MetroFilter;
declare function byName(name: string): MetroFilter;
declare function byProps(...props: string[]): MetroFilter;
declare function byPrototypes(...prototypes: string[]): MetroFilter;
declare function byStore(name: string, short?: boolean): MetroFilter;
declare function clear$1(store: string): void;
declare function clear<
	Func extends (...args: any) => void,
	AwaitTasks extends true | false = false,
>(this: TaskCollection<Func, AwaitTasks>): void;
declare function createPatcher(defaultOptions: string | PatchOptions): PatcherInstance;
declare function defineLocalizations(table: StringStore): Localizations;
declare function destroy(): void;
declare function exists(path: string, inDocuments?: boolean): Promise<boolean>;
declare function fastClear<
	Func extends (...args: any) => void,
	AwaitTasks extends true | false = false,
>(this: TaskCollection<Func, AwaitTasks>): void;
declare function find$1(filter: MetroFilter, options?: MetroSearchOptions): any;
declare function find(filter: (asset: UnboundAsset) => boolean): UnboundAsset | undefined;
declare function findByFilePath<
	U extends string,
	T extends U[] | MetroStringFindWithOptions<U> | MetroBulkFind<U>,
>(...args: T): AnyProps;
declare function findByName<
	U extends string,
	T extends U[] | MetroStringFindWithOptions<U> | MetroBulkFind<U>,
>(...args: T): MetroFunctionSignatureOrArray<T, U>;
declare function findByProps<
	U extends string,
	T extends U[] | MetroStringFindWithOptions<U> | MetroBulkFind<U>,
>(...args: T): MetroPropertyRecordOrArray<T, U> & {};
declare function findByPrototypes<
	U extends string,
	T extends U[] | MetroStringFindWithOptions<U> | MetroBulkFind<U>,
>(...args: T): AnyProps;
declare function findLazy(
	filter: MetroFilter,
	options?: Omit<MetroSearchOptions, 'lazy' | 'all'>,
): any;
declare function findStore<
	U extends string,
	T extends U[] | MetroStringFindWithOptions<U, MetroStoreOptions>,
>(...args: T): AnyProps;
declare function format(key: string, vars?: FormatVars): string;
declare function get<T>(store: string, key: string, def: T): Widen<T>;
declare function getAll(): UnboundAsset[];
declare function getByID(id: number): UnboundAsset | undefined;
declare function getByName(name: string, type?: 'svg' | 'png'): UnboundAsset | undefined;
declare function getIDByName(name: string, type?: 'svg' | 'png'): number | undefined;
declare function getNativeModule<T = any>(...names: string[]): T;
declare function getRuntimeProperties(): Record<string, any>;
declare function getStore(store: string): {
	set: (key: string, value: any) => void;
	get: <T>(key: string, def: T) => Widen<T>;
	toggle: (key: string, def: any) => void;
	remove: (key: string) => void;
	clear: () => void;
	useSettingsStore: (predicate?: (payload: SettingsPayload) => PredicateResult) => {
		set: (key: string, value: any) => void;
		get: <T>(key: string, def: T) => Widen<T>;
		toggle: (key: string, def: any) => void;
		remove: (key: string) => void;
	};
	addListener: (
		predicate: (payload: SettingsPayload) => PredicateResult,
		callback: (payload: SettingsPayload) => void,
	) => () => EventEmitter<EventMap>;
};
declare function growArgsNum<
	Func extends (...args: any) => void,
	AwaitTasks extends true | false = false,
>(this: TaskCollection<Func, AwaitTasks>, argsNum: number): void;
declare function init(): Promise<void>;
declare function initializeModule(id: number): boolean;
declare function instead<M extends PatchParent, P extends PropOf<M>>(
	parent: M,
	method: P,
	callback: PatchCallback<
		M[P] extends (...args: infer Args) => any ? Args : any[],
		M[P] extends (...args: any[]) => infer Res ? Res : any,
		unknown extends ThisParameterType<M[P]> ? M : ThisParameterType<M[P]>
	>,
	options?: PatchOptions,
): () => void;
declare function persist(): Promise<void>;
declare function read(
	path: string,
	encoding?: DCDFileManagerEncoding,
	inDocuments?: boolean,
): Promise<string>;
declare function registerSettings(...entries: SettingsEntry[]): void;
declare function reload(): Promise<void>;
declare function remove(store: string, key: string): void;
declare function removeListener$1(listener: (mdl: any, id: string) => void): void;
declare function removeListener(callback: (payload: SettingsPayload) => void): void;
declare function removeSettings(...keys: string[]): void;
declare function rm(path: string): Promise<boolean>;
declare function sections(): Record<string, SettingsEntry>;
declare function set(store: string, key: string, value: any): void;
declare function setAutoRebuild<
	Func extends (...args: any) => void,
	AwaitTasks extends true | false = false,
>(this: TaskCollection<Func, AwaitTasks>, newVal: boolean): void;
declare function showToast(options: ToastOptions): ToastHandle;
declare function toggle(store: string, key: string, def: any): void;
declare function unpatchAll(): void;
declare function unpatchAllByCaller(caller: string): void;
declare function useSettingsStore(
	store: string,
	predicate?: (payload: SettingsPayload) => PredicateResult,
): {
	set: (key: string, value: any) => void;
	get: <T>(key: string, def: T) => Widen<T>;
	toggle: (key: string, def: any) => void;
	remove: (key: string) => void;
};
declare function write(
	path: string,
	content: string,
	encoding?: DCDFileManagerEncoding,
): Promise<string>;

/** Build and release metadata reported by the native client info module. */
export interface BundleInfoType {
	Version: string;
	ReleaseChannel: string;
	Manifest: string;
	Build: string;
	SentryDsn: string;
	DeviceVendorID: string;
	OTABuild: string;
	SentryStaffDsn: string;
	Identifier: string;
	SentryAlphaBetaDsn: string;
}
/** The native `BundleUpdaterManager` module surface for OTA updates and reloading the bundle. */
export interface DCDBundleManagerType {
	getInitialBundleDownloaded: PromiseFn;
	getInitialOtaUpdateChecked: PromiseFn;
	checkForUpdateAndReload: Fn;
	reload: Fn;
	getOtaRootPath: PromiseFn;
	getBuildOverrideCookieContents: PromiseFn;
	setBuildOverrideCookieHeader: PromiseFn;
	getManifestInfo: PromiseFn;
	addListener: Fn;
	removeListeners: Fn;
}
/** The constant directory paths exposed by the native `DCDFileManager`. */
export interface DCDFileManagerConstants {
	CacheDirPath: string;
	DocumentsDirPath: string;
}
/** The native `DCDFileManager` module surface for reading, writing, and inspecting files. */
export interface DCDFileManagerType extends DCDFileManagerConstants {
	readFile(path: string, encoding: DCDFileManagerEncoding): Promise<string>;
	writeFile(
		type: 'documents' | 'cache',
		path: string,
		data: string,
		encoding: DCDFileManagerEncoding,
	): Promise<string>;
	removeFile(type: 'documents' | 'cache', path: string): Promise<any>;
	readAsset(): Promise<unknown>;
	getSize(): Promise<unknown>;
	getVideoDimensions(): Promise<unknown>;
	fileExists(path: string): Promise<boolean>;
	saveFileToGallery(): Promise<unknown>;
	getConstants(): DCDFileManagerConstants;
}
/** Hardware and OS details reported by the native device module. */
export interface DeviceInfoType {
	isTaskBarEnabled: boolean;
	maxCpuFreq: string;
	socName: string;
	deviceModel: string;
	isTablet: boolean;
	isGestureNavigationEnabled: boolean;
	deviceProduct: string;
	systemVersion: string;
	deviceManufacturer: string;
	deviceBrand: string;
	ramSize: string;
	device: string;
}
/** An asset registered with Discord's packager (its metadata and dimensions). */
export interface DiscordAsset {
	__packager_asset?: boolean;
	name: string;
	httpServerLocation?: string;
	width: number;
	height: number;
	scales: number[];
	hash: string;
	type: string;
	[key: PropertyKey]: any;
}
export interface IEventEmitter<EventMap extends DefaultEventMap = DefaultEventMap> {
	emit<EventKey extends keyof EventMap>(
		event: EventKey,
		...args: Parameters<EventMap[EventKey]>
	): boolean;
	on<EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	): this;
	once<EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	): this;
	addListener<EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	): this;
	removeListener<EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	): this;
	prependListener<EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	): this;
	prependOnceListener<EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	): this;
	off<EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	): this;
	removeAllListeners<EventKey extends keyof EventMap = string>(event?: EventKey): this;
	setMaxListeners(n: number): this;
	getMaxListeners(): number;
	listeners<EventKey extends keyof EventMap = string>(event: EventKey): EventMap[EventKey][];
	rawListeners<EventKey extends keyof EventMap = string>(event: EventKey): EventMap[EventKey][];
	eventNames(): Array<string | symbol>;
	listenerCount<EventKey extends keyof EventMap = string>(type: EventKey): number;
}
/** A single entry in a {@link bulk} search: a filter plus its per-item options. */
export interface MetroBulkItem extends Omit<MetroSearchOptions, 'initial' | 'cache'> {
	filter: MetroFilter;
}
/** Search options for {@link findStore}, adding the `short` name-matching toggle. */
export interface MetroStoreOptions extends MetroSearchOptions {
	short?: boolean;
}
//#endregion
//#region src/env.d.ts
/**
 * A reference to a {@link PatchParent} that does not, by itself, prevent the parent from being
 * garbage collected. Mirrors the subset of the global {@link WeakRef} API that the patcher uses.
 */
export interface ParentRef {
	deref(): PatchParent | undefined;
}
export interface Patch<Args extends any[] = any[], Res = any, Self = any> extends PatchOptions {
	callback: PatchCallback<Args, Res, Self>;
}
export interface PatchCallback<Args extends any[] = any[], Res = any, Self = any> {
	(ctx: PatchContext<Args, Res, Self>): any;
}
export interface PatchContext<Args extends any = any[], Res = any, Self = any> {
	original: (...args: any[]) => Res;
	this: Self;
	result: Res | null;
	args: Args;
}
export interface PatchOptions {
	once?: boolean;
	caller?: string;
}
//#endregion
//#region src/types.d.ts
export interface PatchedModule {
	parent: ParentRef;
	method: PatchMethod;
	original: AnyFunction & AnyConstructor;
	patches: Record<PatchType, Set<Patch<any, any, any>>>;
}
export interface PatcherInstance {
	instead: typeof instead;
	before: typeof before;
	after: typeof after;
	unpatchAll: () => void;
}
/** A registered Unbound settings entry, mirroring Discord's `SETTING_RENDERER_CONFIG` route shape. */
export interface SettingsEntry {
	type: 'route';
	key: string;
	useTitle: () => string;
	parent: string | null;
	section?: string;
	excludeFromDisplay?: boolean;
	IconComponent?: ComponentType<any>;
	screen: SettingsScreen;
}
/** Payload describing a settings change, passed to `changed` listeners and predicates. */
export interface SettingsPayload {
	store: string;
	key: string | null;
	value: any;
}
/** The screen descriptor a settings route entry renders. */
export interface SettingsScreen {
	route: string;
	getComponent: () => ComponentType<any>;
}

/** A button rendered inside a toast. */
export interface ToastButton {
	variant?: 'primary' | 'secondary' | 'tertiary';
	size?: 'sm' | 'md' | 'lg' | 'xl' | '2xl';
	iconPosition?: 'start' | 'end';
	content: string;
	icon?: number;
	onPress: Fn;
}
/** A handle returned when showing a toast, used to update or close it. */
export interface ToastHandle {
	update: (options: Partial<ToastOptions>) => void;
	close: () => void;
}
/** Options accepted when showing a toast. */
export interface ToastOptions {
	title?: string | ComponentType;
	content?: string;
	duration?: number;
	onTimeout?: Fn;
	icon?: string | number | ImageSourcePropType;
	id?: string;
	buttons?: ToastButton[];
	tintedIcon?: boolean;
}

export type AnyConstructor = {
	new (...args: any): any;
};
export type AnyFunction = (...args: any[]) => any;
export type AnyObject = Record<any, any>;
/** An object of shape `T` widened with an arbitrary string/number/symbol index. */
export type AnyProps<T extends Record<PropertyKey, any> = Record<PropertyKey, any>> = T &
	Record<PropertyKey, any>;
export type ArgsNum<T extends (...args: any[]) => any> = T extends (...args: infer K) => any
	? K['length']
	: never;
export type ClearedPayload = {
	store: string;
};
/** The text encodings accepted by the native `DCDFileManager` read/write operations. */
export type DCDFileManagerEncoding = 'utf-8' | 'utf8' | 'base64';
export type DefaultEventMap = {
	[event in string | symbol]: Listener;
} & {
	/**
	 * __proto__ key not allowed due to implementation
	 * add prefix, if you want to use this keyword
	 */
	__proto__?: never;
};
export type EventMap = {
	set: (payload: SetPayload) => void;
	changed: (payload: SettingsPayload) => void;
	cleared: (payload: ClearedPayload) => void;
	removed: (payload: RemovedPayload) => void;
	toggled: (payload: ToggledPayload) => void;
};
/** The set of all falsy values. */
export type Falsy = false | 0 | '' | null | undefined;
/** Any function: accepts any arguments and returns `T`. */
export type Fn<T = any> = (...args: any) => T;
export type FormatVars = Record<string, unknown>;
export type Listener = (...args: any[]) => Promise<any> | void;
export type LocaleStrings = Record<string, string>;
export type Localizations = {
	Messages: Record<string, string>;
	format: (key: string, vars?: FormatVars) => string;
};
/** Widens a single result to an array when the search was made with `all: true`. */
export type MetroAllValues<T extends Record<PropertyKey, any>, U extends unknown> = T extends {
	all: true;
}
	? U[]
	: U;
/** Tuple of param bags followed by a `{ bulk: true }` marker, describing a bulk find. */
export type MetroBulkFind<T extends string> = [
	...AnyProps<MetroParamsBag<T>>[],
	AnyProps<MetroBulkMarker>,
];
/** The marker object distinguishing a bulk find from a single one. */
export type MetroBulkMarker = {
	bulk: true;
};
/** Result shape of a bulk by-name search, one function per requested item. */
export type MetroBulkModuleByName<T extends any[]> = {
	[K in keyof T]: T[K] extends {
		interop: false;
	}
		? {
				default: Fn;
			}
		: Fn;
};
/** Result shape of a bulk by-property search, one record per requested item. */
export type MetroBulkModuleByProperty<T extends any[]> = {
	[K in keyof T]: AnyProps<MetroParamsRecord<T[K]['params']>>;
};
/** A module predicate, carrying its cache key and a `raw` flag, produced by every `by*` helper. */
export type MetroFilter = ((mdl: any, id: number | string) => PredicateResult) & {
	[CACHE_KEY]?: string;
	isRaw?: boolean;
};
/** Dispatches to the bulk or single by-name result shape based on the argument tuple. */
export type MetroFunctionSignatureOrArray<T extends any[], U extends string> =
	T extends MetroBulkFind<U> ? MetroBulkModuleByName<T> : MetroSingleModuleByName<T>;
/** Options that control internal search behaviour shared across every `findBy*` helper. */
export type MetroInternalOptions = {
	bulk?: boolean;
	lazy?: boolean;
};
/** Convenience alias for a by-property result derived from a union of prop names. */
export type MetroModule<TProps extends string> = MetroPropertyRecordOrArray<TProps[], TProps>;
/** A bag carrying a `params` array of prop names. */
export type MetroParamsBag<T extends string> = {
	params: T[];
};
/** A record keyed by the prop names listed in a single bulk item's `params`. */
export type MetroParamsRecord<Params extends PropertyKey[]> = {
	[P in Params[number]]: any;
};
/** Dispatches to the bulk or single by-property result shape based on the argument tuple. */
export type MetroPropertyRecordOrArray<T extends any[], U extends string> =
	T extends MetroBulkFind<U> ? MetroBulkModuleByProperty<T> : MetroSingleModuleByProperty<T>;
/** A record keyed by the non-options entries of a find argument tuple. */
export type MetroPropsRecord<T extends any[]> = {
	[k in Exclude<T[number], Record<PropertyKey, any>>]: any;
};
/** Public options accepted by {@link find} and the `findBy*` family. */
export type MetroSearchOptions = {
	esModules?: boolean;
	interop?: boolean;
	initial?: any[];
	cache?: boolean;
	lazy?: boolean;
	raw?: boolean;
	all?: boolean;
	initialize?: boolean;
};
/** Result shape of a by-name search: the matched function (or its default export). */
export type MetroSingleModuleByName<T extends any[]> = T extends [
	...any,
	infer O extends MetroSearchOptions,
]
	? MetroAllValues<
			O,
			O extends {
				interop: false;
			}
				? {
						default: Fn;
					}
				: Fn
		>
	: Fn;
/** Result shape of a by-property search: a record keyed by the requested props. */
export type MetroSingleModuleByProperty<T extends any[]> = T extends [
	...any,
	infer O extends MetroSearchOptions,
]
	? MetroAllValues<O, AnyProps<MetroPropsRecord<T>>>
	: AnyProps<MetroPropsRecord<T>>;
/** Tuple of search terms followed by a trailing options object. */
export type MetroStringFindWithOptions<T extends string, Options = MetroSearchOptions> = [
	...T[],
	Options,
];
export type PatchMethod = string;
export type PatchParent = AnyFunction | AnyObject;
/** The result of a predicate: any {@link Truthy} or {@link Falsy} value. */
export type PredicateResult = Truthy | Falsy;
/** Any function returning a promise (`T` defaults to `Promise<any>`). */
export type PromiseFn<T = Promise<any>> = (...args: any) => T;
export type PropOf<M> = {
	[K in keyof M]: M[K] extends AnyFunction | AnyConstructor ? Extract<K, string> : never;
}[keyof M];
export type RemovedPayload = {
	store: string;
	key: string;
};
export type SetPayload = {
	store: string;
	key: string;
	value: any;
};
export type StringStore = Record<string, LocaleStrings>;
export type ToggledPayload = {
	store: string;
	key: string;
	prev: any;
	value: any;
};
/** The set of all truthy values. */
export type Truthy = true | number | string | object | symbol | bigint;
/** A {@link DiscordAsset} extended with Unbound's icon-pack overrides. */
export type UnboundAsset = DiscordAsset & {
	iconPackPath?: string;
	iconPackScale?: number;
};
/** Widens a literal type to its primitive base (e.g. `'a'` to `string`, `1` to `number`). */
export type Widen<T> = T extends number
	? number
	: T extends string
		? string
		: T extends boolean
			? boolean
			: T;

declare namespace fs {
	export { Documents, exists, read, rm, write };
}
declare namespace api {
	export { AsyncUsers, Invites, Linking, Messages, Profiles };
}
declare namespace filters {
	export { MetroFilter, byDisplayName, byFilePath, byName, byProps, byPrototypes, byStore };
}
declare namespace common {
	export {
		Assets,
		Clipboard$1 as Clipboard,
		Clyde,
		Commands,
		Constants,
		Dispatcher,
		Flux,
		Gestures,
		MarkdownParser,
		Moment,
		REST,
		Radius,
		React$1 as React,
		ReactNative$1 as ReactNative,
		Reanimated,
		SVG,
		Screens,
		Theme$1 as Theme,
		Util,
		i18n,
	};
}
declare namespace stores {
	export { Guilds, Theme$2 as Theme, Users };
}
declare namespace settings$1 {
	export { registerSettings, removeSettings, sections };
}
declare namespace patcher {
	export {
		AnyConstructor,
		AnyFunction,
		AnyObject,
		PATCH_SYMBOL,
		Patch,
		PatchCallback,
		PatchContext,
		PatchMethod,
		PatchOptions,
		PatchParent,
		PatchType,
		PatchedModule,
		PatcherInstance,
		PropOf,
		after,
		before,
		createPatcher,
		instead,
		patches,
		unpatchAll,
		unpatchAllByCaller,
	};
}
declare namespace storage {
	export {
		SettingsPayload,
		addListener,
		clear$1 as clear,
		get,
		getStore,
		off,
		on,
		persist,
		remove,
		removeListener,
		set,
		toggle,
		useSettingsStore,
	};
}
declare namespace assets$1 {
	export { Icons$1 as Icons, assets, find, getAll, getByID, getByName, getIDByName };
}
declare namespace native {
	export {
		BundleInfo,
		BundleInfoType,
		BundleManager,
		DCDBundleManagerType,
		DCDFileManagerConstants,
		DCDFileManagerEncoding,
		DCDFileManagerType,
		DeviceInfo,
		DeviceInfoType,
		UnboundNative$1 as UnboundNative,
		getNativeModule,
		getRuntimeProperties,
		reload,
	};
}
declare namespace toasts {
	export { showToast };
}
declare namespace metro {
	export {
		MetroAllValues,
		MetroBulkFind,
		MetroBulkItem,
		MetroBulkModuleByName,
		MetroBulkModuleByProperty,
		MetroFunctionSignatureOrArray,
		MetroInternalOptions,
		MetroModule,
		MetroPropertyRecordOrArray,
		MetroSearchOptions,
		MetroSingleModuleByName,
		MetroSingleModuleByProperty,
		MetroStoreOptions,
		MetroStringFindWithOptions,
		addListener$1 as addListener,
		api,
		bulk,
		common,
		filters,
		find$1 as find,
		findByFilePath,
		findByName,
		findByProps,
		findByPrototypes,
		findLazy,
		findStore,
		initializeModule,
		off$1 as off,
		on$1 as on,
		removeListener$1 as removeListener,
		stores,
	};
}
declare namespace i18n$1 {
	export { Messages$1 as Messages, defineLocalizations, destroy, format, init };
}

export {
	assets$1 as assets,
	fs,
	i18n$1 as i18n,
	metro,
	native,
	patcher,
	settings$1 as settings,
	storage,
	toasts,
};

export {};
