// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT

//#region src/patcher.d.ts
export declare const PATCH_SYMBOL: unique symbol;
export declare const patches: PatchedModule[];
export declare enum PatchType {
	Before = 0,
	Instead = 1,
	After = 2,
}
export declare function after<M extends PatchParent, P extends PropOf<M>>(
	parent: M,
	method: P,
	callback: PatchCallback<
		M[P] extends (...args: infer Args) => any ? Args : any[],
		M[P] extends (...args: any[]) => infer Res ? Res : any,
		unknown extends ThisParameterType<M[P]> ? M : ThisParameterType<M[P]>
	>,
	options?: PatchOptions,
): () => void;
export declare function before<M extends PatchParent, P extends PropOf<M>>(
	parent: M,
	method: P,
	callback: PatchCallback<
		M[P] extends (...args: infer Args) => any ? Args : any[],
		M[P] extends (...args: any[]) => infer Res ? Res : any,
		unknown extends ThisParameterType<M[P]> ? M : ThisParameterType<M[P]>
	>,
	options?: PatchOptions,
): () => void;
export declare function createPatcher(defaultOptions: string | PatchOptions): PatcherInstance;
export declare function instead<M extends PatchParent, P extends PropOf<M>>(
	parent: M,
	method: P,
	callback: PatchCallback<
		M[P] extends (...args: infer Args) => any ? Args : any[],
		M[P] extends (...args: any[]) => infer Res ? Res : any,
		unknown extends ThisParameterType<M[P]> ? M : ThisParameterType<M[P]>
	>,
	options?: PatchOptions,
): () => void;
export declare function unpatchAll(): void;
export declare function unpatchAllByCaller(caller: string): void;
//#endregion
//#region src/env.d.ts
/**
 * A reference to a {@link PatchParent} that does not, by itself, prevent the parent from being
 * garbage collected. Mirrors the subset of the global {@link WeakRef} API that the patcher uses.
 */
export interface ParentRef {
	deref(): PatchParent | undefined;
}
export interface Patch<Args extends any[] = any[], Res = any, Self = any> extends PatchOptions {
	callback: PatchCallback<Args, Res, Self>;
}
export interface PatchCallback<Args extends any[] = any[], Res = any, Self = any> {
	(ctx: PatchContext<Args, Res, Self>): any;
}
export interface PatchContext<Args extends any = any[], Res = any, Self = any> {
	original: (...args: any[]) => Res;
	this: Self;
	result: Res | null;
	args: Args;
}
export interface PatchOptions {
	once?: boolean;
	caller?: string;
}
//#endregion
//#region src/types.d.ts
export interface PatchedModule {
	parent: ParentRef;
	method: PatchMethod;
	original: AnyFunction & AnyConstructor;
	patches: Record<PatchType, Set<Patch<any, any, any>>>;
}
export interface PatcherInstance {
	instead: typeof instead;
	before: typeof before;
	after: typeof after;
	unpatchAll: () => void;
}
export type AnyConstructor = {
	new (...args: any): any;
};
export type AnyFunction = (...args: any[]) => any;
export type AnyObject = Record<any, any>;
export type PatchMethod = string;
export type PatchParent = AnyFunction | AnyObject;
export type PropOf<M> = {
	[K in keyof M]: M[K] extends AnyFunction | AnyConstructor ? Extract<K, string> : never;
}[keyof M];

export {};
