// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT

import { ComponentType } from 'react';

declare const _default: {
	registerSettings: typeof registerSettings;
	removeSettings: typeof removeSettings;
	sections: typeof sections;
};
/**
 * @description Registers one or more settings entries into the section registry, warning on key collisions.
 * @param entries The settings entries to register.
 */
export declare function registerSettings(...entries: SettingsEntry[]): void;
/**
 * @description Removes one or more settings entries from the section registry by key.
 * @param keys The entry keys to remove.
 */
export declare function removeSettings(...keys: string[]): void;
/**
 * @description Returns the current registry of settings entries.
 * @returns A record of entry key to its {@link SettingsEntry}.
 */
export declare function sections(): Record<string, SettingsEntry>;
/** A registered Unbound settings entry, mirroring Discord's `SETTING_RENDERER_CONFIG` route shape. */
export interface SettingsEntry {
	type: 'route';
	key: string;
	useTitle: () => string;
	parent: string | null;
	section?: string;
	excludeFromDisplay?: boolean;
	IconComponent?: ComponentType<any>;
	screen: SettingsScreen;
}
/** The screen descriptor a settings route entry renders. */
export interface SettingsScreen {
	route: string;
	getComponent: () => ComponentType<any>;
}

export { _default as default };

export {};
