// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT

import type { SettingsEntry } from './utilities';
import { ComponentType } from 'react';

declare const _default: {
	registerSettings: typeof registerSettings;
	removeSettings: typeof removeSettings;
	sections: typeof sections;
};
/**
 * @description Registers one or more settings entries into the section registry, warning on key collisions.
 * @param entries The settings entries to register.
 */
export declare function registerSettings(...entries: SettingsEntry[]): void;
/**
 * @description Removes one or more settings entries from the section registry by key.
 * @param keys The entry keys to remove.
 */
export declare function removeSettings(...keys: string[]): void;
/**
 * @description Returns the current registry of settings entries.
 * @returns A record of entry key to its {@link SettingsEntry}.
 */
export declare function sections(): Record<string, SettingsEntry>;
export { _default as default };

export {};
