// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT

declare class EventEmitter<
	EventMap extends DefaultEventMap = DefaultEventMap,
> implements IEventEmitter<EventMap> {
	events: {
		[eventName in keyof EventMap]?: TaskCollection<EventMap[eventName]>;
	};
	onceEvents: {
		[eventName in keyof EventMap]?: EventMap[eventName][] | EventMap[eventName];
	};
	boundFuncs: undefined | Map<Function, Function>;
	_symbolKeys: Set<symbol>;
	maxListeners: number;
	get _eventsCount(): number;
	emit: <EventKey extends keyof EventMap>(
		event: EventKey,
		...args: Parameters<EventMap[EventKey]>
	) => boolean;
	on: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => this;
	once: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => this;
	addListener: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
		argsNum?: ArgsNum<EventMap[EventKey]>,
	) => this;
	removeListener: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => this;
	hasListeners: <EventKey extends keyof EventMap = string>(event: EventKey) => boolean;
	prependListener: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => this;
	prependOnceListener: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => this;
	off: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => this;
	removeAllListeners: <EventKey extends keyof EventMap = string>(event?: EventKey) => this;
	setMaxListeners: (n: number) => this;
	getMaxListeners: () => number;
	listeners: <EventKey extends keyof EventMap = string>(event: EventKey) => EventMap[EventKey][];
	rawListeners: <EventKey extends keyof EventMap = string>(
		event: EventKey,
	) => EventMap[EventKey][];
	eventNames: () => Array<string | symbol>;
	listenerCount: <EventKey extends keyof EventMap = string>(type: EventKey) => number;
	addListenerBound: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
		bindTo?: any,
		argsNum?: ArgsNum<EventMap[EventKey]>,
	) => this;
	removeListenerBound: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => this;
}
declare class TaskCollection<
	Func extends (...args: any) => void,
	AwaitTasks extends true | false = false,
> {
	readonly awaitTasks: AwaitTasks;
	constructor(
		argsNum: ArgsNum<Func>,
		autoRebuild?: boolean,
		initialTasks?: Func[] | Func | null,
		awaitTasks?: AwaitTasks,
	);
	/** DO NOT CHANGE DIRECTLY */
	_tasks: Func[] | Func | null;
	/** cached */
	length: number;
	/** auto rebuild on first emit call; otherwise autorebuild on every change */
	firstEmitBuildStrategy: boolean;
	readonly argsNum: ArgsNum<Func>;
	autoRebuild: boolean;
	readonly growArgsNum: typeof growArgsNum;
	setAutoRebuild: typeof setAutoRebuild;
	call: (...args: Parameters<Func>) => AwaitTasks extends true ? Promise<void> : void;
	rebuild: () => void;
	push: (...func: Func[]) => void;
	/** remove last matched task from tasks */
	removeLast: (func: Func) => void;
	insert: (index: number, ...func: Func[]) => void;
	setTasks: (tasks: Func[]) => void;
	tasksAsArray: () => Func[];
	/** this autorebuilds */
	readonly clear: typeof clear;
	/** this autorebuilds */
	readonly fastClear: typeof fastClear;
}
declare const _default: {
	addListener: typeof addListener;
	get: typeof get;
	getStore: typeof getStore;
	off: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => EventEmitter<EventMap>;
	on: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => EventEmitter<EventMap>;
	persist: typeof persist;
	remove: typeof remove;
	removeListener: typeof removeListener;
	set: typeof set;
	useSettingsStore: typeof useSettingsStore;
};
/**
 * @description Removes an entire store and all of its keys, and emits `changed` and `cleared`.
 * @param store The store to clear.
 */
declare function clear$1(store: string): void;
declare function clear<
	Func extends (...args: any) => void,
	AwaitTasks extends true | false = false,
>(this: TaskCollection<Func, AwaitTasks>): void;
declare function fastClear<
	Func extends (...args: any) => void,
	AwaitTasks extends true | false = false,
>(this: TaskCollection<Func, AwaitTasks>): void;
declare function growArgsNum<
	Func extends (...args: any) => void,
	AwaitTasks extends true | false = false,
>(this: TaskCollection<Func, AwaitTasks>, argsNum: number): void;
declare function setAutoRebuild<
	Func extends (...args: any) => void,
	AwaitTasks extends true | false = false,
>(this: TaskCollection<Func, AwaitTasks>, newVal: boolean): void;
export declare const off: <EventKey extends keyof EventMap = string>(
	event: EventKey,
	listener: EventMap[EventKey],
) => EventEmitter<EventMap>;
export declare const on: <EventKey extends keyof EventMap = string>(
	event: EventKey,
	listener: EventMap[EventKey],
) => EventEmitter<EventMap>;
/**
 * @description Registers a callback invoked on every settings change matching the predicate.
 * @param predicate Decides whether a given change should fire the callback.
 * @param callback Invoked with the payload of each matching change.
 * @returns A function that removes the listener.
 */
export declare function addListener(
	predicate: (payload: SettingsPayload) => PredicateResult,
	callback: (payload: SettingsPayload) => void,
): () => EventEmitter<EventMap>;
/**
 * @description Reads a value from a store by dot-separated key path, falling back to a default when absent.
 * @template T The type of the default value.
 * @param store The store to read from.
 * @param key The dot-separated key path within the store.
 * @param def The value to return when the key is not set.
 * @returns The stored value, or `def` if the key path is not present.
 */
export declare function get<T>(store: string, key: string, def: T): Widen<T>;
/**
 * @description Builds a store-scoped facade binding every settings operation to a single store name.
 * @param store The store name to scope every operation to.
 * @returns An object exposing `get`, `set`, `toggle`, `remove`, `clear`, `useSettingsStore`, and `addListener` bound to the store.
 */
export declare function getStore(store: string): {
	set: (key: string, value: any) => void;
	get: <T>(key: string, def: T) => Widen<T>;
	toggle: (key: string, def: any) => void;
	remove: (key: string) => void;
	clear: () => void;
	useSettingsStore: (predicate?: (payload: SettingsPayload) => PredicateResult) => {
		set: (key: string, value: any) => void;
		get: <T>(key: string, def: T) => Widen<T>;
		toggle: (key: string, def: any) => void;
		remove: (key: string) => void;
	};
	addListener: (
		predicate: (payload: SettingsPayload) => PredicateResult,
		callback: (payload: SettingsPayload) => void,
	) => () => EventEmitter<EventMap>;
};
/**
 * @description Serialises the current settings and writes them to disk.
 * @returns A promise that resolves once the settings file has been written.
 */
export declare function persist(): Promise<void>;
/**
 * @description Deletes a top-level key from a store, dropping the store entirely if it becomes empty, and emits `changed` and `removed`.
 * @param store The store to remove the key from.
 * @param key The key to delete.
 */
export declare function remove(store: string, key: string): void;
/**
 * @description Removes a previously registered settings change listener.
 * @param callback The listener to remove.
 */
export declare function removeListener(callback: (payload: SettingsPayload) => void): void;
/**
 * @description Writes a value into a store at a dot-separated key path, creating intermediate objects, and emits `changed` and `set`.
 * @param store The store to write to.
 * @param key The dot-separated key path within the store.
 * @param value The value to store.
 */
export declare function set(store: string, key: string, value: any): void;
/**
 * @description Flips a boolean value at a key path against its current (or default) value, and emits `toggled`.
 * @param store The store to write to.
 * @param key The dot-separated key path within the store.
 * @param def The value to assume when the key is not yet set.
 */
export declare function toggle(store: string, key: string, def: any): void;
/**
 * @description React hook that re-renders the component whenever a matching change occurs in the store.
 * @param store The store to subscribe to.
 * @param predicate Optional filter deciding which changes trigger a re-render.
 * @returns An object exposing `get`, `set`, `toggle`, and `remove` bound to the store.
 */
export declare function useSettingsStore(
	store: string,
	predicate?: (payload: SettingsPayload) => PredicateResult,
): {
	set: (key: string, value: any) => void;
	get: <T>(key: string, def: T) => Widen<T>;
	toggle: (key: string, def: any) => void;
	remove: (key: string) => void;
};
export interface IEventEmitter<EventMap extends DefaultEventMap = DefaultEventMap> {
	emit<EventKey extends keyof EventMap>(
		event: EventKey,
		...args: Parameters<EventMap[EventKey]>
	): boolean;
	on<EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	): this;
	once<EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	): this;
	addListener<EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	): this;
	removeListener<EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	): this;
	prependListener<EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	): this;
	prependOnceListener<EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	): this;
	off<EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	): this;
	removeAllListeners<EventKey extends keyof EventMap = string>(event?: EventKey): this;
	setMaxListeners(n: number): this;
	getMaxListeners(): number;
	listeners<EventKey extends keyof EventMap = string>(event: EventKey): EventMap[EventKey][];
	rawListeners<EventKey extends keyof EventMap = string>(event: EventKey): EventMap[EventKey][];
	eventNames(): Array<string | symbol>;
	listenerCount<EventKey extends keyof EventMap = string>(type: EventKey): number;
}
/** Payload describing a settings change, passed to `changed` listeners and predicates. */
export interface SettingsPayload {
	store: string;
	key: string | null;
	value: any;
}
export type ArgsNum<T extends (...args: any[]) => any> = T extends (...args: infer K) => any
	? K['length']
	: never;
export type ClearedPayload = {
	store: string;
};
export type DefaultEventMap = {
	[event in string | symbol]: Listener;
} & {
	/**
	 * __proto__ key not allowed due to implementation
	 * add prefix, if you want to use this keyword
	 */
	__proto__?: never;
};
export type EventMap = {
	set: (payload: SetPayload) => void;
	changed: (payload: SettingsPayload) => void;
	cleared: (payload: ClearedPayload) => void;
	removed: (payload: RemovedPayload) => void;
	toggled: (payload: ToggledPayload) => void;
};
/** The set of all falsy values. */
export type Falsy = false | 0 | '' | null | undefined;
export type Listener = (...args: any[]) => Promise<any> | void;
/** The result of a predicate: any {@link Truthy} or {@link Falsy} value. */
export type PredicateResult = Truthy | Falsy;
export type RemovedPayload = {
	store: string;
	key: string;
};
export type SetPayload = {
	store: string;
	key: string;
	value: any;
};
export type ToggledPayload = {
	store: string;
	key: string;
	prev: any;
	value: any;
};
/** The set of all truthy values. */
export type Truthy = true | number | string | object | symbol | bigint;
/** Widens a literal type to its primitive base (e.g. `'a'` to `string`, `1` to `number`). */
export type Widen<T> = T extends number
	? number
	: T extends string
		? string
		: T extends boolean
			? boolean
			: T;

export { _default as default, clear$1 as clear };

export {};
