// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT

import type { EventEmitter } from './tseep';
import type { PredicateResult, Widen } from './utils';
declare const _default: {
	addListener: typeof addListener;
	get: typeof get;
	getStore: typeof getStore;
	off: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => EventEmitter<EventMap>;
	on: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => EventEmitter<EventMap>;
	persist: typeof persist;
	remove: typeof remove;
	removeListener: typeof removeListener;
	set: typeof set;
	useSettingsStore: typeof useSettingsStore;
};
/**
 * @description Removes an entire store and all of its keys, and emits `changed` and `cleared`.
 * @param store The store to clear.
 */
declare function clear$1(store: string): void;
export declare const off: <EventKey extends keyof EventMap = string>(
	event: EventKey,
	listener: EventMap[EventKey],
) => EventEmitter<EventMap>;
export declare const on: <EventKey extends keyof EventMap = string>(
	event: EventKey,
	listener: EventMap[EventKey],
) => EventEmitter<EventMap>;
/**
 * @description Registers a callback invoked on every settings change matching the predicate.
 * @param predicate Decides whether a given change should fire the callback.
 * @param callback Invoked with the payload of each matching change.
 * @returns A function that removes the listener.
 */
export declare function addListener(
	predicate: (payload: SettingsPayload) => PredicateResult,
	callback: (payload: SettingsPayload) => void,
): () => EventEmitter<EventMap>;
/**
 * @description Reads a value from a store by dot-separated key path, falling back to a default when absent.
 * @template T The type of the default value.
 * @param store The store to read from.
 * @param key The dot-separated key path within the store.
 * @param def The value to return when the key is not set.
 * @returns The stored value, or `def` if the key path is not present.
 */
export declare function get<T>(store: string, key: string, def: T): Widen<T>;
/**
 * @description Builds a store-scoped facade binding every settings operation to a single store name.
 * @param store The store name to scope every operation to.
 * @returns An object exposing `get`, `set`, `toggle`, `remove`, `clear`, `useSettingsStore`, and `addListener` bound to the store.
 */
export declare function getStore(store: string): {
	set: (key: string, value: any) => void;
	get: <T>(key: string, def: T) => Widen<T>;
	toggle: (key: string, def: any) => void;
	remove: (key: string) => void;
	clear: () => void;
	useSettingsStore: (predicate?: (payload: SettingsPayload) => PredicateResult) => {
		set: (key: string, value: any) => void;
		get: <T>(key: string, def: T) => Widen<T>;
		toggle: (key: string, def: any) => void;
		remove: (key: string) => void;
	};
	addListener: (
		predicate: (payload: SettingsPayload) => PredicateResult,
		callback: (payload: SettingsPayload) => void,
	) => () => EventEmitter<EventMap>;
};
/**
 * @description Serialises the current settings and writes them to disk.
 * @returns A promise that resolves once the settings file has been written.
 */
export declare function persist(): Promise<void>;
/**
 * @description Deletes a top-level key from a store, dropping the store entirely if it becomes empty, and emits `changed` and `removed`.
 * @param store The store to remove the key from.
 * @param key The key to delete.
 */
export declare function remove(store: string, key: string): void;
/**
 * @description Removes a previously registered settings change listener.
 * @param callback The listener to remove.
 */
export declare function removeListener(callback: (payload: SettingsPayload) => void): void;
/**
 * @description Writes a value into a store at a dot-separated key path, creating intermediate objects, and emits `changed` and `set`.
 * @param store The store to write to.
 * @param key The dot-separated key path within the store.
 * @param value The value to store.
 */
export declare function set(store: string, key: string, value: any): void;
/**
 * @description Flips a boolean value at a key path against its current (or default) value, and emits `toggled`.
 * @param store The store to write to.
 * @param key The dot-separated key path within the store.
 * @param def The value to assume when the key is not yet set.
 */
export declare function toggle(store: string, key: string, def: any): void;
/**
 * @description React hook that re-renders the component whenever a matching change occurs in the store.
 * @param store The store to subscribe to.
 * @param predicate Optional filter deciding which changes trigger a re-render.
 * @returns An object exposing `get`, `set`, `toggle`, and `remove` bound to the store.
 */
export declare function useSettingsStore(
	store: string,
	predicate?: (payload: SettingsPayload) => PredicateResult,
): {
	set: (key: string, value: any) => void;
	get: <T>(key: string, def: T) => Widen<T>;
	toggle: (key: string, def: any) => void;
	remove: (key: string) => void;
};

/** Payload describing a settings change, passed to `changed` listeners and predicates. */
export interface SettingsPayload {
	store: string;
	key: string | null;
	value: any;
}

export type ClearedPayload = {
	store: string;
};
export type EventMap = {
	set: (payload: SetPayload) => void;
	changed: (payload: SettingsPayload) => void;
	cleared: (payload: ClearedPayload) => void;
	removed: (payload: RemovedPayload) => void;
	toggled: (payload: ToggledPayload) => void;
};
export type RemovedPayload = {
	store: string;
	key: string;
};
export type SetPayload = {
	store: string;
	key: string;
	value: any;
};
export type ToggledPayload = {
	store: string;
	key: string;
	prev: any;
	value: any;
};
export { _default as default, clear$1 as clear };

export {};
