// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT

export type { ToastHandle, ToastOptions } from './_internal';
import { ImageSourcePropType } from 'react-native';
import { ComponentType } from 'react';

import type { ToastHandle, ToastOptions } from './_internal';

declare const _default: {
	showToast: typeof showToast;
};
/**
 * @description Shows a toast, generating an id when one is not supplied.
 * @param options The toast options, optionally including a custom `id`.
 * @returns A {@link ToastHandle} for controlling the shown toast.
 */
export declare function showToast(options: ToastOptions): ToastHandle;
export { _default as default };
