// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT

import { ComponentType } from 'react';
import { ImageSourcePropType } from 'react-native';

declare const _default: {
	showToast: typeof showToast;
};
/**
 * @description Shows a toast, generating an id when one is not supplied.
 * @param options The toast options, optionally including a custom `id`.
 * @returns A {@link ToastHandle} for controlling the shown toast.
 */
export declare function showToast(options: ToastOptions): ToastHandle;
/** A button rendered inside a toast. */
export interface ToastButton {
	variant?: 'primary' | 'secondary' | 'tertiary';
	size?: 'sm' | 'md' | 'lg' | 'xl' | '2xl';
	iconPosition?: 'start' | 'end';
	content: string;
	icon?: number;
	onPress: Fn;
}
/** A handle returned when showing a toast, used to update or close it. */
export interface ToastHandle {
	update: (options: Partial<ToastOptions>) => void;
	close: () => void;
}
/** Options accepted when showing a toast. */
export interface ToastOptions {
	title?: string | ComponentType;
	content?: string;
	duration?: number;
	onTimeout?: Fn;
	icon?: string | number | ImageSourcePropType;
	id?: string;
	buttons?: ToastButton[];
	tintedIcon?: boolean;
}
/** Any function: accepts any arguments and returns `T`. */
export type Fn<T = any> = (...args: any) => T;

export { _default as default };

export {};
