// Auto-generated by generate-plugin-sdk.ts - DO NOT EDIT

declare class TaskCollection<
	Func extends (...args: any) => void,
	AwaitTasks extends true | false = false,
> {
	readonly awaitTasks: AwaitTasks;
	constructor(
		argsNum: ArgsNum<Func>,
		autoRebuild?: boolean,
		initialTasks?: Func[] | Func | null,
		awaitTasks?: AwaitTasks,
	);
	/** DO NOT CHANGE DIRECTLY */
	_tasks: Func[] | Func | null;
	/** cached */
	length: number;
	/** auto rebuild on first emit call; otherwise autorebuild on every change */
	firstEmitBuildStrategy: boolean;
	readonly argsNum: ArgsNum<Func>;
	autoRebuild: boolean;
	readonly growArgsNum: typeof growArgsNum;
	setAutoRebuild: typeof setAutoRebuild;
	call: (...args: Parameters<Func>) => AwaitTasks extends true ? Promise<void> : void;
	rebuild: () => void;
	push: (...func: Func[]) => void;
	/** remove last matched task from tasks */
	removeLast: (func: Func) => void;
	insert: (index: number, ...func: Func[]) => void;
	setTasks: (tasks: Func[]) => void;
	tasksAsArray: () => Func[];
	/** this autorebuilds */
	readonly clear: typeof clear;
	/** this autorebuilds */
	readonly fastClear: typeof fastClear;
}
declare function clear<
	Func extends (...args: any) => void,
	AwaitTasks extends true | false = false,
>(this: TaskCollection<Func, AwaitTasks>): void;
declare function fastClear<
	Func extends (...args: any) => void,
	AwaitTasks extends true | false = false,
>(this: TaskCollection<Func, AwaitTasks>): void;
declare function growArgsNum<
	Func extends (...args: any) => void,
	AwaitTasks extends true | false = false,
>(this: TaskCollection<Func, AwaitTasks>, argsNum: number): void;
declare function setAutoRebuild<
	Func extends (...args: any) => void,
	AwaitTasks extends true | false = false,
>(this: TaskCollection<Func, AwaitTasks>, newVal: boolean): void;

/** Implemented event emitter */
export declare class EventEmitter<
	EventMap extends DefaultEventMap = DefaultEventMap,
> implements IEventEmitter<EventMap> {
	events: {
		[eventName in keyof EventMap]?: TaskCollection<EventMap[eventName]>;
	};
	onceEvents: {
		[eventName in keyof EventMap]?: EventMap[eventName][] | EventMap[eventName];
	};
	boundFuncs: undefined | Map<Function, Function>;
	_symbolKeys: Set<symbol>;
	maxListeners: number;
	get _eventsCount(): number;
	emit: <EventKey extends keyof EventMap>(
		event: EventKey,
		...args: Parameters<EventMap[EventKey]>
	) => boolean;
	on: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => this;
	once: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => this;
	addListener: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
		argsNum?: ArgsNum<EventMap[EventKey]>,
	) => this;
	removeListener: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => this;
	hasListeners: <EventKey extends keyof EventMap = string>(event: EventKey) => boolean;
	prependListener: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => this;
	prependOnceListener: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => this;
	off: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => this;
	removeAllListeners: <EventKey extends keyof EventMap = string>(event?: EventKey) => this;
	setMaxListeners: (n: number) => this;
	getMaxListeners: () => number;
	listeners: <EventKey extends keyof EventMap = string>(event: EventKey) => EventMap[EventKey][];
	rawListeners: <EventKey extends keyof EventMap = string>(
		event: EventKey,
	) => EventMap[EventKey][];
	eventNames: () => Array<string | symbol>;
	listenerCount: <EventKey extends keyof EventMap = string>(type: EventKey) => number;
	addListenerBound: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
		bindTo?: any,
		argsNum?: ArgsNum<EventMap[EventKey]>,
	) => this;
	removeListenerBound: <EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	) => this;
}
export interface IEventEmitter<EventMap extends DefaultEventMap = DefaultEventMap> {
	emit<EventKey extends keyof EventMap>(
		event: EventKey,
		...args: Parameters<EventMap[EventKey]>
	): boolean;
	on<EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	): this;
	once<EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	): this;
	addListener<EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	): this;
	removeListener<EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	): this;
	prependListener<EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	): this;
	prependOnceListener<EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	): this;
	off<EventKey extends keyof EventMap = string>(
		event: EventKey,
		listener: EventMap[EventKey],
	): this;
	removeAllListeners<EventKey extends keyof EventMap = string>(event?: EventKey): this;
	setMaxListeners(n: number): this;
	getMaxListeners(): number;
	listeners<EventKey extends keyof EventMap = string>(event: EventKey): EventMap[EventKey][];
	rawListeners<EventKey extends keyof EventMap = string>(event: EventKey): EventMap[EventKey][];
	eventNames(): Array<string | symbol>;
	listenerCount<EventKey extends keyof EventMap = string>(type: EventKey): number;
}
export type ArgsNum<T extends (...args: any[]) => any> = T extends (...args: infer K) => any
	? K['length']
	: never;
export type DefaultEventMap = {
	[event in string | symbol]: Listener;
} & {
	/**
	 * __proto__ key not allowed due to implementation
	 * add prefix, if you want to use this keyword
	 */
	__proto__?: never;
};
export type Listener = (...args: any[]) => Promise<any> | void;
